require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RepositoryCompactsController do

  # This should return the minimal set of attributes required to create a valid
  # RepositoryCompact. As you add validations to RepositoryCompact, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RepositoryCompactsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all repository_compacts as @repository_compacts" do
      repository_compact = RepositoryCompact.create! valid_attributes
      get :index, {}, valid_session
      assigns(:repository_compacts).should eq([repository_compact])
    end
  end

  describe "GET show" do
    it "assigns the requested repository_compact as @repository_compact" do
      repository_compact = RepositoryCompact.create! valid_attributes
      get :show, {:id => repository_compact.to_param}, valid_session
      assigns(:repository_compact).should eq(repository_compact)
    end
  end

  describe "GET new" do
    it "assigns a new repository_compact as @repository_compact" do
      get :new, {}, valid_session
      assigns(:repository_compact).should be_a_new(RepositoryCompact)
    end
  end

  describe "GET edit" do
    it "assigns the requested repository_compact as @repository_compact" do
      repository_compact = RepositoryCompact.create! valid_attributes
      get :edit, {:id => repository_compact.to_param}, valid_session
      assigns(:repository_compact).should eq(repository_compact)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RepositoryCompact" do
        expect {
          post :create, {:repository_compact => valid_attributes}, valid_session
        }.to change(RepositoryCompact, :count).by(1)
      end

      it "assigns a newly created repository_compact as @repository_compact" do
        post :create, {:repository_compact => valid_attributes}, valid_session
        assigns(:repository_compact).should be_a(RepositoryCompact)
        assigns(:repository_compact).should be_persisted
      end

      it "redirects to the created repository_compact" do
        post :create, {:repository_compact => valid_attributes}, valid_session
        response.should redirect_to(RepositoryCompact.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved repository_compact as @repository_compact" do
        # Trigger the behavior that occurs when invalid params are submitted
        RepositoryCompact.any_instance.stub(:save).and_return(false)
        post :create, {:repository_compact => { "name" => "invalid value" }}, valid_session
        assigns(:repository_compact).should be_a_new(RepositoryCompact)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RepositoryCompact.any_instance.stub(:save).and_return(false)
        post :create, {:repository_compact => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested repository_compact" do
        repository_compact = RepositoryCompact.create! valid_attributes
        # Assuming there are no other repository_compacts in the database, this
        # specifies that the RepositoryCompact created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RepositoryCompact.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => repository_compact.to_param, :repository_compact => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested repository_compact as @repository_compact" do
        repository_compact = RepositoryCompact.create! valid_attributes
        put :update, {:id => repository_compact.to_param, :repository_compact => valid_attributes}, valid_session
        assigns(:repository_compact).should eq(repository_compact)
      end

      it "redirects to the repository_compact" do
        repository_compact = RepositoryCompact.create! valid_attributes
        put :update, {:id => repository_compact.to_param, :repository_compact => valid_attributes}, valid_session
        response.should redirect_to(repository_compact)
      end
    end

    describe "with invalid params" do
      it "assigns the repository_compact as @repository_compact" do
        repository_compact = RepositoryCompact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RepositoryCompact.any_instance.stub(:save).and_return(false)
        put :update, {:id => repository_compact.to_param, :repository_compact => { "name" => "invalid value" }}, valid_session
        assigns(:repository_compact).should eq(repository_compact)
      end

      it "re-renders the 'edit' template" do
        repository_compact = RepositoryCompact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RepositoryCompact.any_instance.stub(:save).and_return(false)
        put :update, {:id => repository_compact.to_param, :repository_compact => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested repository_compact" do
      repository_compact = RepositoryCompact.create! valid_attributes
      expect {
        delete :destroy, {:id => repository_compact.to_param}, valid_session
      }.to change(RepositoryCompact, :count).by(-1)
    end

    it "redirects to the repository_compacts list" do
      repository_compact = RepositoryCompact.create! valid_attributes
      delete :destroy, {:id => repository_compact.to_param}, valid_session
      response.should redirect_to(repository_compacts_url)
    end
  end

end
