require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChunksController do

  # This should return the minimal set of attributes required to create a valid
  # Chunk. As you add validations to Chunk, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all chunks as @chunks" do
      chunk = Chunk.create! valid_attributes
      get :index
      assigns(:chunks).should eq([chunk])
    end
  end

  describe "GET show" do
    it "assigns the requested chunk as @chunk" do
      chunk = Chunk.create! valid_attributes
      get :show, :id => chunk.id
      assigns(:chunk).should eq(chunk)
    end
  end

  describe "GET new" do
    it "assigns a new chunk as @chunk" do
      get :new
      assigns(:chunk).should be_a_new(Chunk)
    end
  end

  describe "GET edit" do
    it "assigns the requested chunk as @chunk" do
      chunk = Chunk.create! valid_attributes
      get :edit, :id => chunk.id
      assigns(:chunk).should eq(chunk)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Chunk" do
        expect {
          post :create, :chunk => valid_attributes
        }.to change(Chunk, :count).by(1)
      end

      it "assigns a newly created chunk as @chunk" do
        post :create, :chunk => valid_attributes
        assigns(:chunk).should be_a(Chunk)
        assigns(:chunk).should be_persisted
      end

      it "redirects to the created chunk" do
        post :create, :chunk => valid_attributes
        response.should redirect_to(Chunk.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chunk as @chunk" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chunk.any_instance.stub(:save).and_return(false)
        post :create, :chunk => {}
        assigns(:chunk).should be_a_new(Chunk)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chunk.any_instance.stub(:save).and_return(false)
        post :create, :chunk => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chunk" do
        chunk = Chunk.create! valid_attributes
        # Assuming there are no other chunks in the database, this
        # specifies that the Chunk created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Chunk.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => chunk.id, :chunk => {'these' => 'params'}
      end

      it "assigns the requested chunk as @chunk" do
        chunk = Chunk.create! valid_attributes
        put :update, :id => chunk.id, :chunk => valid_attributes
        assigns(:chunk).should eq(chunk)
      end

      it "redirects to the chunk" do
        chunk = Chunk.create! valid_attributes
        put :update, :id => chunk.id, :chunk => valid_attributes
        response.should redirect_to(chunk)
      end
    end

    describe "with invalid params" do
      it "assigns the chunk as @chunk" do
        chunk = Chunk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chunk.any_instance.stub(:save).and_return(false)
        put :update, :id => chunk.id, :chunk => {}
        assigns(:chunk).should eq(chunk)
      end

      it "re-renders the 'edit' template" do
        chunk = Chunk.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chunk.any_instance.stub(:save).and_return(false)
        put :update, :id => chunk.id, :chunk => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chunk" do
      chunk = Chunk.create! valid_attributes
      expect {
        delete :destroy, :id => chunk.id
      }.to change(Chunk, :count).by(-1)
    end

    it "redirects to the chunks list" do
      chunk = Chunk.create! valid_attributes
      delete :destroy, :id => chunk.id
      response.should redirect_to(chunks_url)
    end
  end

end
