require 'spec_helper'

describe WebconfRoomsController do
  describe "routing" do

    # standard routes generated by bigbluebutton_rails
    it {
      should route(:get, "/manage/webconf/rooms").
        to(:action => :index)
    }
    it {
      should route(:get, "/manage/webconf/rooms/new").
        to(:action => :new)
    }
    it {
      should route(:get, "/manage/webconf/rooms/external").
        to(:action => :external)
    }
    it {
      should route(:post, "/manage/webconf/rooms/external").
        to(:action => :external_auth)
    }
    it {
      should route(:get, "/manage/webconf/rooms/room-1/edit").
        to(:action => :edit, :id => "room-1")
    }
    it {
      should route(:get, "/manage/webconf/rooms/room-1").
        to(:action => :show, :id => "room-1")
    }
    it {
      should route(:put, "/manage/webconf/rooms/room-1").
        to(:action => :update, :id => "room-1")
    }
    it {
      should route(:delete, "/manage/webconf/rooms/room-1").
        to(:action => :destroy, :id => "room-1")
    }
    it {
      should route(:get, "/manage/webconf/rooms/room-1/join").
        to(:action => :join, :id => "room-1")
    }
    it {
      should route(:get, "/manage/webconf/rooms/room-1/join_mobile").
        to(:action => :join_mobile, :id => "room-1")
    }
    it {
      should route(:get, "/manage/webconf/rooms/room-1/running").
        to(:action => :running, :id => "room-1")
    }
    it {
      should route(:get, "/manage/webconf/rooms/room-1/end").
        to(:action => :end, :id => "room-1")
    }
    it {
      should route(:get, "/manage/webconf/rooms/room-1/invite").
        to(:action => :invite, :id => "room-1")
    }
    it {
      should route(:post, "/manage/webconf/rooms/room-1/join").
        to(:action => :auth, :id => "room-1")
    }

    it { {:get => "/webconf/room-1"}.should route_to(:controller => "webconf_rooms", :action => "invite", :id => "room-1") }

  end
end
