/*
 * File automatically generated by
 * gengen 1.0 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "file_save.h"

void
file_save_gen_class::generate_file_save(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  if (check_given)
    {
      stream << "if (args_info->";
      generate_string (given, stream, indent + indent_str.length ());
      stream << ") {";
      stream << "\n";
      stream << indent_str;
    }
  if (has_arg)
    {
      stream << "  if (args_info->";
      generate_string (arg, stream, indent + indent_str.length ());
      stream << ") {";
      stream << "\n";
      stream << indent_str;
      stream << "    fprintf(outfile, \"%s=\\\"%s\\\"\\n\", \"";
      generate_string (opt_name, stream, indent + indent_str.length ());
      stream << "\", args_info->";
      generate_string (arg, stream, indent + indent_str.length ());
      stream << ");";
      stream << "\n";
      stream << indent_str;
      stream << "  } else {";
      stream << "\n";
      stream << indent_str;
      stream << "    fprintf(outfile, \"%s\\n\", \"";
      generate_string (opt_name, stream, indent + indent_str.length ());
      stream << "\");";
      stream << "\n";
      stream << indent_str;
      stream << "  }";
      stream << "\n";
      stream << indent_str;
    }
  else
    {
      stream << "  fprintf(outfile, \"%s\\n\", \"";
      generate_string (opt_name, stream, indent + indent_str.length ());
      stream << "\");";
      stream << "\n";
      stream << indent_str;
    }
  if (check_given)
    {
      stream << "}";
      stream << "\n";
      stream << indent_str;
    }
}
