// DO NOT EDIT! Auto-generated by github.com/mgutz/razor

package cases

import (
	"cases/layout/base"
	"github.com/mgutz/razor"
	. "kp/models"
	"tpl/helper"
)

// Home is generated
func Home() *razor.SafeBuffer {
	__buffer := razor.NewSafeBuffer()
	var totalMessage int
	var u *User
	__buffer.WriteSafe(helper.Header())
	__buffer.WriteSafe(helper.Msg(u))
	for i := 0; i < 2; i++ {
		if totalMessage > 0 {
			if totalMessage == 1 {

				__buffer.WriteString("<p>")
				__buffer.WriteSafe(u.Name)
				__buffer.WriteString(" has 1 message</p>")

			} else {

				__buffer.WriteString("<p>")
				__buffer.WriteSafe(u.Name)
				__buffer.WriteString(" has ")
				__buffer.WriteSafe(gorazor.Itoa(totalMessage))
				__buffer.WriteString(" messages</p>")

			}
		} else {

			__buffer.WriteString("<p>")
			__buffer.WriteSafe(u.Name)
			__buffer.WriteString(" has no messages</p>")

		}
	}
	{
		for i := 0; i < 2; i++ {
			if totalMessage > 0 {
				if totalMessage == 1 {

					__buffer.WriteString("<p>")
					__buffer.WriteSafe(u.Name)
					__buffer.WriteString(" has 1 message</p>")

				} else {

					__buffer.WriteString("<p>")
					__buffer.WriteSafe(u.Name)
					__buffer.WriteString(" has ")
					__buffer.WriteSafe(gorazor.Itoa(totalMessage))
					__buffer.WriteString(" messages</p>")

				}
			} else {

				__buffer.WriteString("<p>")
				__buffer.WriteSafe(u.Name)
				__buffer.WriteString(" has no messages</p>")

			}
		}
	}
	{
		switch totalMessage {
		case 1:

			__buffer.WriteString("<p>")
			__buffer.WriteSafe(u.Name)
			__buffer.WriteString(" has 1  message</p>")

		case 2:

			__buffer.WriteString("<p>")
			__buffer.WriteSafe(u.Name)
			__buffer.WriteString(" has 2 messages</p>")

		default:

			__buffer.WriteString("<p>")
			__buffer.WriteSafe(u.Name)
			__buffer.WriteString(" has no messages</p>")

		}
	}
	__buffer.WriteSafe(helper.Footer())

	__title := func() *razor.SafeBuffer {
		__buffer := razor.NewSafeBuffer()

		__buffer.WriteString("<title>")
		__buffer.WriteSafe(u.Name)
		__buffer.WriteString("'s homepage</title>")

		return __buffer
	}

	__side := func() *razor.SafeBuffer {
		__buffer := razor.NewSafeBuffer()

		return __buffer
	}

	return __buffer
}
