package rabbitmq_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RabbitmqBrokerJob struct {

	/*RabbitmqBroker - Descr: Logging level Default: info
*/
	RabbitmqBroker *RabbitmqBroker `yaml:"rabbitmq-broker,omitempty"`

	/*Cf - Descr: Domain shared by the UAA and CF API, e.g. 'bosh-lite.com' Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

	/*SyslogAggregator - Descr: Syslog drain port Default: <nil>
*/
	SyslogAggregator *SyslogAggregator `yaml:"syslog_aggregator,omitempty"`

}