// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/activatedio/simplestack/netboot (interfaces: DispatchTFTPReadHandler,TFTPReadHandlerFactory)

package netboot_mocks

import (
	server "github.com/activatedio/simplestack/server"
	gomock "github.com/golang/mock/gomock"
)

// Mock of DispatchTFTPReadHandler interface
type MockDispatchTFTPReadHandler struct {
	ctrl     *gomock.Controller
	recorder *_MockDispatchTFTPReadHandlerRecorder
}

// Recorder for MockDispatchTFTPReadHandler (not exported)
type _MockDispatchTFTPReadHandlerRecorder struct {
	mock *MockDispatchTFTPReadHandler
}

func NewMockDispatchTFTPReadHandler(ctrl *gomock.Controller) *MockDispatchTFTPReadHandler {
	mock := &MockDispatchTFTPReadHandler{ctrl: ctrl}
	mock.recorder = &_MockDispatchTFTPReadHandlerRecorder{mock}
	return mock
}

func (_m *MockDispatchTFTPReadHandler) EXPECT() *_MockDispatchTFTPReadHandlerRecorder {
	return _m.recorder
}

func (_m *MockDispatchTFTPReadHandler) Register(_param0 string, _param1 server.TFTPReadHandler) {
	_m.ctrl.Call(_m, "Register", _param0, _param1)
}

func (_mr *_MockDispatchTFTPReadHandlerRecorder) Register(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Register", arg0, arg1)
}

// Mock of TFTPReadHandlerFactory interface
type MockTFTPReadHandlerFactory struct {
	ctrl     *gomock.Controller
	recorder *_MockTFTPReadHandlerFactoryRecorder
}

// Recorder for MockTFTPReadHandlerFactory (not exported)
type _MockTFTPReadHandlerFactoryRecorder struct {
	mock *MockTFTPReadHandlerFactory
}

func NewMockTFTPReadHandlerFactory(ctrl *gomock.Controller) *MockTFTPReadHandlerFactory {
	mock := &MockTFTPReadHandlerFactory{ctrl: ctrl}
	mock.recorder = &_MockTFTPReadHandlerFactoryRecorder{mock}
	return mock
}

func (_m *MockTFTPReadHandlerFactory) EXPECT() *_MockTFTPReadHandlerFactoryRecorder {
	return _m.recorder
}

func (_m *MockTFTPReadHandlerFactory) Create(_param0 interface{}) (server.TFTPReadHandler, error) {
	ret := _m.ctrl.Call(_m, "Create", _param0)
	ret0, _ := ret[0].(server.TFTPReadHandler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockTFTPReadHandlerFactoryRecorder) Create(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Create", arg0)
}
