package v1

// This file contains methods that can be used by the go-restful package to generate Swagger
// documentation for the object types found in 'types.go' This file is automatically generated
// by hack/update-generated-swagger-descriptions.sh and should be run after a full build of OpenShift.
// ==== DO NOT EDIT THIS FILE MANUALLY ====

var map_ServiceBroker = map[string]string{
	"":         "ServiceBroker describe a servicebroker",
	"metadata": "Standard object's metadata.",
	"spec":     "Spec defines the behavior of the Namespace.",
	"status":   "Status describes the current status of a Namespace",
}

func (ServiceBroker) SwaggerDoc() map[string]string {
	return map_ServiceBroker
}

var map_ServiceBrokerList = map[string]string{
	"":         "ServiceBrokerList is a list of ServiceBroker objects.",
	"metadata": "Standard object's metadata.",
	"items":    "Items is a list of routes",
}

func (ServiceBrokerList) SwaggerDoc() map[string]string {
	return map_ServiceBrokerList
}

var map_ServiceBrokerSpec = map[string]string{
	"":           "ServiceBrokerSpec describes the attributes on a ServiceBroker",
	"url":        "url defines the address of a ServiceBroker service",
	"name":       "name defines the name of a ServiceBroker service",
	"username":   "username defines the username to access ServiceBroker service",
	"password":   "password defines the password to access ServiceBroker service",
	"finalizers": "Finalizers is an opaque list of values that must be empty to permanently remove object from storage",
}

func (ServiceBrokerSpec) SwaggerDoc() map[string]string {
	return map_ServiceBrokerSpec
}

var map_ServiceBrokerStatus = map[string]string{
	"":      "ServiceBrokerStatus is information about the current status of a ServiceBroker",
	"phase": "Phase is the current lifecycle phase of the project",
}

func (ServiceBrokerStatus) SwaggerDoc() map[string]string {
	return map_ServiceBrokerStatus
}
