
// generated by gocc; DO NOT EDIT.

package lexer



/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates] func(rune) int

var TransTab = TransitionTable{
	
		// S0
		func(r rune) int {
			switch {
			case r == 9 : // ['\t','\t']
				return 1
			case r == 10 : // ['\n','\n']
				return 1
			case r == 13 : // ['\r','\r']
				return 1
			case r == 32 : // [' ',' ']
				return 1
			case r == 33 : // ['!','!']
				return 2
			case r == 34 : // ['"','"']
				return 3
			case r == 39 : // [''',''']
				return 4
			case r == 40 : // ['(','(']
				return 5
			case r == 41 : // [')',')']
				return 6
			case 48 <= r && r <= 57 : // ['0','9']
				return 7
			case r == 60 : // ['<','<']
				return 8
			case r == 61 : // ['=','=']
				return 9
			case r == 62 : // ['>','>']
				return 10
			case 65 <= r && r <= 90 : // ['A','Z']
				return 11
			case r == 97 : // ['a','a']
				return 12
			case r == 98 : // ['b','b']
				return 11
			case r == 99 : // ['c','c']
				return 13
			case r == 100 : // ['d','d']
				return 11
			case r == 101 : // ['e','e']
				return 14
			case r == 102 : // ['f','f']
				return 15
			case 103 <= r && r <= 104 : // ['g','h']
				return 11
			case r == 105 : // ['i','i']
				return 16
			case 106 <= r && r <= 108 : // ['j','l']
				return 11
			case r == 109 : // ['m','m']
				return 17
			case r == 110 : // ['n','n']
				return 18
			case r == 111 : // ['o','o']
				return 19
			case 112 <= r && r <= 115 : // ['p','s']
				return 11
			case r == 116 : // ['t','t']
				return 20
			case r == 117 : // ['u','u']
				return 21
			case 118 <= r && r <= 122 : // ['v','z']
				return 11
			
			
			
			}
			return NoState
			
		},
	
		// S1
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S2
		func(r rune) int {
			switch {
			case r == 61 : // ['=','=']
				return 22
			
			
			
			}
			return NoState
			
		},
	
		// S3
		func(r rune) int {
			switch {
			case r == 34 : // ['"','"']
				return 23
			
			
			default:
				return 3
			}
			
		},
	
		// S4
		func(r rune) int {
			switch {
			case r == 39 : // [''',''']
				return 23
			
			
			default:
				return 4
			}
			
		},
	
		// S5
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S6
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S7
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 24
			case 48 <= r && r <= 57 : // ['0','9']
				return 7
			
			
			
			}
			return NoState
			
		},
	
		// S8
		func(r rune) int {
			switch {
			case r == 61 : // ['=','=']
				return 25
			
			
			
			}
			return NoState
			
		},
	
		// S9
		func(r rune) int {
			switch {
			case r == 61 : // ['=','=']
				return 26
			
			
			
			}
			return NoState
			
		},
	
		// S10
		func(r rune) int {
			switch {
			case r == 61 : // ['=','=']
				return 27
			
			
			
			}
			return NoState
			
		},
	
		// S11
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S12
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 109 : // ['a','m']
				return 30
			case r == 110 : // ['n','n']
				return 31
			case 111 <= r && r <= 122 : // ['o','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S13
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 110 : // ['a','n']
				return 30
			case r == 111 : // ['o','o']
				return 32
			case 112 <= r && r <= 122 : // ['p','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S14
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 108 : // ['a','l']
				return 30
			case r == 109 : // ['m','m']
				return 33
			case 110 <= r && r <= 122 : // ['n','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S15
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case r == 97 : // ['a','a']
				return 34
			case 98 <= r && r <= 122 : // ['b','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S16
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 114 : // ['a','r']
				return 30
			case r == 115 : // ['s','s']
				return 35
			case 116 <= r && r <= 122 : // ['t','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S17
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case r == 97 : // ['a','a']
				return 36
			case 98 <= r && r <= 122 : // ['b','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S18
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 110 : // ['a','n']
				return 30
			case r == 111 : // ['o','o']
				return 37
			case 112 <= r && r <= 116 : // ['p','t']
				return 30
			case r == 117 : // ['u','u']
				return 38
			case 118 <= r && r <= 122 : // ['v','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S19
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 113 : // ['a','q']
				return 30
			case r == 114 : // ['r','r']
				return 39
			case 115 <= r && r <= 122 : // ['s','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S20
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 113 : // ['a','q']
				return 30
			case r == 114 : // ['r','r']
				return 40
			case 115 <= r && r <= 122 : // ['s','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S21
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 109 : // ['a','m']
				return 30
			case r == 110 : // ['n','n']
				return 41
			case 111 <= r && r <= 122 : // ['o','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S22
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S23
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S24
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 24
			case 48 <= r && r <= 57 : // ['0','9']
				return 42
			
			
			
			}
			return NoState
			
		},
	
		// S25
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S26
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S27
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S28
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S29
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S30
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S31
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 99 : // ['a','c']
				return 30
			case r == 100 : // ['d','d']
				return 43
			case 101 <= r && r <= 122 : // ['e','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S32
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 109 : // ['a','m']
				return 30
			case r == 110 : // ['n','n']
				return 44
			case 111 <= r && r <= 122 : // ['o','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S33
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 111 : // ['a','o']
				return 30
			case r == 112 : // ['p','p']
				return 45
			case 113 <= r && r <= 122 : // ['q','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S34
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 107 : // ['a','k']
				return 30
			case r == 108 : // ['l','l']
				return 46
			case 109 <= r && r <= 122 : // ['m','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S35
		func(r rune) int {
			switch {
			case r == 32 : // [' ',' ']
				return 47
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S36
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 115 : // ['a','s']
				return 30
			case r == 116 : // ['t','t']
				return 48
			case 117 <= r && r <= 122 : // ['u','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S37
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 115 : // ['a','s']
				return 30
			case r == 116 : // ['t','t']
				return 49
			case 117 <= r && r <= 122 : // ['u','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S38
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 107 : // ['a','k']
				return 30
			case r == 108 : // ['l','l']
				return 50
			case 109 <= r && r <= 122 : // ['m','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S39
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S40
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 116 : // ['a','t']
				return 30
			case r == 117 : // ['u','u']
				return 51
			case 118 <= r && r <= 122 : // ['v','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S41
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 99 : // ['a','c']
				return 30
			case r == 100 : // ['d','d']
				return 52
			case 101 <= r && r <= 122 : // ['e','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S42
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 24
			case 48 <= r && r <= 57 : // ['0','9']
				return 42
			
			
			
			}
			return NoState
			
		},
	
		// S43
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S44
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 115 : // ['a','s']
				return 30
			case r == 116 : // ['t','t']
				return 53
			case 117 <= r && r <= 122 : // ['u','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S45
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 115 : // ['a','s']
				return 30
			case r == 116 : // ['t','t']
				return 54
			case 117 <= r && r <= 122 : // ['u','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S46
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 114 : // ['a','r']
				return 30
			case r == 115 : // ['s','s']
				return 55
			case 116 <= r && r <= 122 : // ['t','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S47
		func(r rune) int {
			switch {
			case r == 110 : // ['n','n']
				return 56
			
			
			
			}
			return NoState
			
		},
	
		// S48
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 98 : // ['a','b']
				return 30
			case r == 99 : // ['c','c']
				return 57
			case 100 <= r && r <= 122 : // ['d','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S49
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S50
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 107 : // ['a','k']
				return 30
			case r == 108 : // ['l','l']
				return 58
			case 109 <= r && r <= 122 : // ['m','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S51
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 100 : // ['a','d']
				return 30
			case r == 101 : // ['e','e']
				return 59
			case 102 <= r && r <= 122 : // ['f','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S52
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 100 : // ['a','d']
				return 30
			case r == 101 : // ['e','e']
				return 60
			case 102 <= r && r <= 122 : // ['f','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S53
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case r == 97 : // ['a','a']
				return 61
			case 98 <= r && r <= 122 : // ['b','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S54
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 120 : // ['a','x']
				return 30
			case r == 121 : // ['y','y']
				return 62
			case r == 122 : // ['z','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S55
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 100 : // ['a','d']
				return 30
			case r == 101 : // ['e','e']
				return 63
			case 102 <= r && r <= 122 : // ['f','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S56
		func(r rune) int {
			switch {
			case r == 111 : // ['o','o']
				return 64
			
			
			
			}
			return NoState
			
		},
	
		// S57
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 103 : // ['a','g']
				return 30
			case r == 104 : // ['h','h']
				return 65
			case 105 <= r && r <= 122 : // ['i','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S58
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S59
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S60
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 101 : // ['a','e']
				return 30
			case r == 102 : // ['f','f']
				return 66
			case 103 <= r && r <= 122 : // ['g','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S61
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 104 : // ['a','h']
				return 30
			case r == 105 : // ['i','i']
				return 67
			case 106 <= r && r <= 122 : // ['j','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S62
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S63
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S64
		func(r rune) int {
			switch {
			case r == 116 : // ['t','t']
				return 68
			
			
			
			}
			return NoState
			
		},
	
		// S65
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 100 : // ['a','d']
				return 30
			case r == 101 : // ['e','e']
				return 69
			case 102 <= r && r <= 122 : // ['f','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S66
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 104 : // ['a','h']
				return 30
			case r == 105 : // ['i','i']
				return 70
			case 106 <= r && r <= 122 : // ['j','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S67
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 109 : // ['a','m']
				return 30
			case r == 110 : // ['n','n']
				return 71
			case 111 <= r && r <= 122 : // ['o','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S68
		func(r rune) int {
			switch {
			
			
			
			}
			return NoState
			
		},
	
		// S69
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 114 : // ['a','r']
				return 30
			case r == 115 : // ['s','s']
				return 72
			case 116 <= r && r <= 122 : // ['t','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S70
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 109 : // ['a','m']
				return 30
			case r == 110 : // ['n','n']
				return 73
			case 111 <= r && r <= 122 : // ['o','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S71
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 114 : // ['a','r']
				return 30
			case r == 115 : // ['s','s']
				return 74
			case 116 <= r && r <= 122 : // ['t','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S72
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S73
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 100 : // ['a','d']
				return 30
			case r == 101 : // ['e','e']
				return 75
			case 102 <= r && r <= 122 : // ['f','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S74
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S75
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 99 : // ['a','c']
				return 30
			case r == 100 : // ['d','d']
				return 76
			case 101 <= r && r <= 122 : // ['e','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
		// S76
		func(r rune) int {
			switch {
			case r == 46 : // ['.','.']
				return 28
			case 48 <= r && r <= 57 : // ['0','9']
				return 29
			case 65 <= r && r <= 90 : // ['A','Z']
				return 30
			case r == 95 : // ['_','_']
				return 28
			case 97 <= r && r <= 122 : // ['a','z']
				return 30
			
			
			
			}
			return NoState
			
		},
	
}
