<?php
namespace Sagres\Component\FileSystem;



/**
 * Test class for Copy.
 * Generated by PHPUnit on 2012-03-19 at 16:40:12.
 */
class CopyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Copy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        @mkdir($this->getFixturesPath('copy'));



        $this->object = new Copy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        // take care of copy folder
        @unlink($this->getFixturesPath('copy/read.write.file'));
        @unlink($this->getFixturesPath('copy/copied.file'));

        @rmdir($this->getFixturesPath('copy'));
    }

    private function getFixturesPath($path)
    {
        return __DIR__ . '/../../../fixtures/' . $path;
    }

    /**
     * @covers Sagres\Component\FileSystem\Copy::copy
     * @covers Sagres\Component\FileSystem\Copy::createNode
     * @covers Sagres\Component\FileSystem\Copy::computeFinalDestination
     */
    public function testCopy()
    {

        $this->object->copy($this->getFixturesPath('read.write.file'), $this->getFixturesPath('copy/copied.file'));
        $this->assertTrue(file_exists($this->getFixturesPath('copy/copied.file')));
    }
    /**
     * @covers Sagres\Component\FileSystem\Copy::copy
     * @covers Sagres\Component\FileSystem\Copy::createNode
     * @covers Sagres\Component\FileSystem\Copy::computeFinalDestination
     */
    public function testCopy_folder()
    {

        $this->object->copy($this->getFixturesPath('read.write.file'), $this->getFixturesPath('copy/'));
        $this->assertTrue(file_exists($this->getFixturesPath('copy/read.write.file')));
    }

    /**
     * @covers Sagres\Component\FileSystem\Copy::copy
     * @covers Sagres\Component\FileSystem\Copy::createNode
     * @covers Sagres\Component\FileSystem\Copy::computeFinalDestination
     *
     * @expectedException UnexpectedValueException
     */
    public function testCopy_source_is_folder()
    {

        $this->object->copy($this->getFixturesPath(''), $this->getFixturesPath('copy/'));
    }

    /**
     * @covers Sagres\Component\FileSystem\Copy::copy
     * @covers Sagres\Component\FileSystem\Copy::createNode
     * @covers Sagres\Component\FileSystem\Copy::computeFinalDestination
     *
     * @expectedException Sagres\Component\FileSystem\Exception\ResourceExistsException
     */
    public function testCopy_no_overwrite()
    {

        $this->object->copy($this->getFixturesPath('read.write.file'), $this->getFixturesPath(''));
    }

    /**
     * @covers Sagres\Component\FileSystem\Copy::copyFolder
     * @todo Implement testCopyFolder().
     */
    public function testCopyFolder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
