<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DocumentRepository\Module'                        => __DIR__ . '/Module.php',
    'DocumentRepository\Controller\DocumentRepositoryController' => __DIR__ . '/src/DocumentRepository/Controller/DocumentRepositoryController.php',
    'DocumentRepositoryTest\Framework\TestCase'        => __DIR__ . '/tests/DocumentRepository/Framework/TestCase.php',
    'DocumentRepositoryTest\SampleTest'                => __DIR__ . '/tests/DocumentRepository/SampleTest.php',
);
