<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DtlCustomer\Form\CustomerReference'                   => __DIR__ . '/src/DtlCustomer/Form/CustomerReference.php',
  'DtlCustomer\Form\Fieldset\CustomerReference'          => __DIR__ . '/src/DtlCustomer/Form/Fieldset/CustomerReference.php',
  'DtlCustomer\Form\Fieldset\CustomerBankAccount'        => __DIR__ . '/src/DtlCustomer/Form/Fieldset/CustomerBankAccount.php',
  'DtlCustomer\Form\Fieldset\CustomerPatrimony'          => __DIR__ . '/src/DtlCustomer/Form/Fieldset/CustomerPatrimony.php',
  'DtlCustomer\Form\Fieldset\Customer'                   => __DIR__ . '/src/DtlCustomer/Form/Fieldset/Customer.php',
  'DtlCustomer\Form\CustomerBankAccount'                 => __DIR__ . '/src/DtlCustomer/Form/CustomerBankAccount.php',
  'DtlCustomer\Form\CustomerPatrimony'                   => __DIR__ . '/src/DtlCustomer/Form/CustomerPatrimony.php',
  'DtlCustomer\Form\Customer'                            => __DIR__ . '/src/DtlCustomer/Form/Customer.php',
  'DtlCustomer\Factory\CustomerReference'                => __DIR__ . '/src/DtlCustomer/Factory/CustomerReference.php',
  'DtlCustomer\Factory\CustomerBankAccount'              => __DIR__ . '/src/DtlCustomer/Factory/CustomerBankAccount.php',
  'DtlCustomer\Factory\CustomerPatrimony'                => __DIR__ . '/src/DtlCustomer/Factory/CustomerPatrimony.php',
  'DtlCustomer\Factory\Customer'                         => __DIR__ . '/src/DtlCustomer/Factory/Customer.php',
  'DtlCustomer\Controller\CustomerPatrimonyController'   => __DIR__ . '/src/DtlCustomer/Controller/CustomerPatrimonyController.php',
  'DtlCustomer\Controller\CustomerBankAccountController' => __DIR__ . '/src/DtlCustomer/Controller/CustomerBankAccountController.php',
  'DtlCustomer\Controller\CustomerController'            => __DIR__ . '/src/DtlCustomer/Controller/CustomerController.php',
  'DtlCustomer\Controller\CustomerReferenceController'   => __DIR__ . '/src/DtlCustomer/Controller/CustomerReferenceController.php',
  'DtlCustomer\Entity\Repository\Customer'               => __DIR__ . '/src/DtlCustomer/Entity/Repository/Customer.php',
  'DtlCustomer\Entity\Customer'                          => __DIR__ . '/src/DtlCustomer/Entity/Customer.php',
  'DtlCustomer\Module'                                   => __DIR__ . '/Module.php',
);
