<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Customer\Module'                               => __DIR__ . '/Module.php',
    'Customer\Service\CustomerServiceFactory'       => __DIR__ . '/src/Customer/Service/CustomerServiceFactory.php',
    'Customer\Service\CustomerService'              => __DIR__ . '/src/Customer/Service/CustomerService.php',
    'Customer\View\Helper\CustomerAddress'          => __DIR__ . '/src/Customer/View/Helper/CustomerAddress.php',
    'Customer\Table\CustomerTableFactory'           => __DIR__ . '/src/Customer/Table/CustomerTableFactory.php',
    'Customer\Table\CustomerTable'                  => __DIR__ . '/src/Customer/Table/CustomerTable.php',
    'Customer\InputFilter\CustomerFilter'           => __DIR__ . '/src/Customer/InputFilter/CustomerFilter.php',
    'Customer\InputFilter\CustomerAddressFilter'    => __DIR__ . '/src/Customer/InputFilter/CustomerAddressFilter.php',
    'Customer\Hydrator\CustomerDbHydrator'          => __DIR__ . '/src/Customer/Hydrator/CustomerDbHydrator.php',
    'Customer\Entity\CustomerEntity'                => __DIR__ . '/src/Customer/Entity/CustomerEntity.php',
    'Customer\Entity\AddressEntity'                 => __DIR__ . '/src/Customer/Entity/AddressEntity.php',
    'Customer\Form\CustomerForm'                    => __DIR__ . '/src/Customer/Form/CustomerForm.php',
    'Customer\Form\CustomerFormFactory'             => __DIR__ . '/src/Customer/Form/CustomerFormFactory.php',
    'Customer\Form\CustomerAddressFieldset'         => __DIR__ . '/src/Customer/Form/CustomerAddressFieldset.php',
    'Customer\Controller\CustomerController'        => __DIR__ . '/src/Customer/Controller/CustomerController.php',
    'Customer\Controller\CustomerControllerFactory' => __DIR__ . '/src/Customer/Controller/CustomerControllerFactory.php',
    'Customer\Validator\Country'                    => __DIR__ . '/src/Customer/Validator/Country.php',
    'Customer\Validator\CountryFactory'             => __DIR__ . '/src/Customer/Validator/CountryFactory.php',
);
