<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'lund-customer/retailer/view'   => __DIR__ . '/view/lund-customer/retailer/view.phtml',
    'lund-customer/retailer/create' => __DIR__ . '/view/lund-customer/retailer/create.phtml',
    'lund-customer/retailer/index'  => __DIR__ . '/view/lund-customer/retailer/index.phtml',
    'lund-customer/retailer/edit'   => __DIR__ . '/view/lund-customer/retailer/edit.phtml',
    'lund-customer/customer/view'   => __DIR__ . '/view/lund-customer/customer/view.phtml',
    'lund-customer/customer/create' => __DIR__ . '/view/lund-customer/customer/create.phtml',
    'lund-customer/customer/index'  => __DIR__ . '/view/lund-customer/customer/index.phtml',
    'lund-customer/customer/edit'   => __DIR__ . '/view/lund-customer/customer/edit.phtml',
);
