<?php

namespace ShopBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{

    public static function checkIfUserExistByEmail($repository, $email)
    {
        $repository = $repository->getRepository('ShopBundle:Users');
        $user = $repository->findOneByEmail($email);
        return $user;
    }

    public static function loginUser($repository, $email, $password)
    {
        $repository = $repository->getRepository('ShopBundle:Users');
        $user = $repository->findOneBy(array("email" => $email, "password" => md5($password)));

        if ($user) {
            return true;
        } else {
            return false;
        }
    }

}
