#!/usr/bin/env python

import sys
import collections
import threading

import avalanche

from snotstream import jsonserver
from snotstream import dispatch
from snotstream import fifo

fifonames = ('nhit', 'crateevent', 'cardevent', 'craterate')

if __name__ == '__main__':
    address = sys.argv[1] if len(sys.argv)>1 else 'tcp://*:5024'

    fifos = {}
    for name in fifonames:
        fifos[name] = fifo.RingBuffer(100)

    try:
        dispatch_client = dispatch.DispatchClient(address, fifos)
        print 'snotstream: starting dispatcher client'
        dispatch_client.start()

        httpd = jsonserver.JSONServer('', 8051, fifos)
        print 'snotstream: starting json server'
        httpd.serve_forever()

    except KeyboardInterrupt, SystemExit:
        print 'snotstream: caught SIGINT, exiting'
        dispatch_client.request_exit = True
        dispatch_client.join()

