#!/usr/bin/env python

import SimpleHTTPServer

class BrokerHTTPServer(SimpleHTTPServer.SimpleHTTPRequestHandler):
    SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map.update({
        '': 'application/json' # Default
    })

    def translate_path(self, path):
        _path = SimpleHTTPServer.SimpleHTTPRequestHandler.translate_path(self, path)
        if path.startswith('/broker/'):
            _path = _path.rstrip('/') + '.' + self.command.lower()
        return _path

    do_POST = SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET

import sys, os
sys.argv.append(os.environ.get('PORT', '9090'))
SimpleHTTPServer.test(HandlerClass=BrokerHTTPServer)
