# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('manage_organization', 'can manage an organization'),
                                     ('view_affiliations', 'can view affiliated people'),
                                     ('manage_affiliations', 'can manage affiliations'),
                                     ('offer_affiliations', 'can offer affiliations'),
                                     ('manage_roles', 'can manage roles'))},
        ),
    ]
