#!/bin/bash

set -eu

mkdir repo
mkdir repo/conf

cat <<EOF >repo/conf/distributions
Codename: wheezy
Architectures: i386 amd64 source
Components: main contrib non-free
EOF

APTIREPO_ROOTDIR=repo aptirepo updatedists

assert_find repo/dists \
"repo/dists/wheezy/contrib/binary-amd64/Packages
repo/dists/wheezy/contrib/binary-amd64/Packages.gz
repo/dists/wheezy/contrib/binary-i386/Packages
repo/dists/wheezy/contrib/binary-i386/Packages.gz
repo/dists/wheezy/contrib/Contents.gz
repo/dists/wheezy/contrib/source/Sources
repo/dists/wheezy/contrib/source/Sources.gz
repo/dists/wheezy/main/binary-amd64/Packages
repo/dists/wheezy/main/binary-amd64/Packages.gz
repo/dists/wheezy/main/binary-i386/Packages
repo/dists/wheezy/main/binary-i386/Packages.gz
repo/dists/wheezy/main/Contents.gz
repo/dists/wheezy/main/source/Sources
repo/dists/wheezy/main/source/Sources.gz
repo/dists/wheezy/non-free/binary-amd64/Packages
repo/dists/wheezy/non-free/binary-amd64/Packages.gz
repo/dists/wheezy/non-free/binary-i386/Packages
repo/dists/wheezy/non-free/binary-i386/Packages.gz
repo/dists/wheezy/non-free/Contents.gz
repo/dists/wheezy/non-free/source/Sources
repo/dists/wheezy/non-free/source/Sources.gz
repo/dists/wheezy/Release" \
'-type f'

assert_find repo/pool \
"repo/pool/contrib
repo/pool/main
repo/pool/non-free" \
'-type d -links 2'
