#!/bin/sh

# In the following directories, files of WL520g/SnapAP will be different
# usage: [MODELID] [Language] [MODELSTR]
echo Make $1 Web Page

if [ -n "$1" ] && [ -n "$2" ] && [ -n "$3" ]; then

	MODEL="$1"
	MODELID="$MODEL"
	MODEL_STR="$3"
	MODEL_DIR=web_"$MODEL"_"$2"
	MODEL_SIZE="$4"

	rm -rf ./web
	cp -rf ./$MODEL_DIR ./web

	echo $MODEL_DIR

	### 1. copy all files to tempdir ###
	cp -rf ./web/. ./web_$MODEL
	rm -rf ./web_$MODEL/*.asp
	cd ./web

	### 2. Replace ProductID in *.asp and *.js ###

	LIST=`ls *.asp`
	PATTERN="s/ZVMODELVZ/$MODEL_STR/g"

	echo $PATTERN

	# Embed Module ID to *.asp
	for i in $LIST; do
		# echo $i $1
		cat $i | sed "$PATTERN" > ../web_$MODEL/$i
	done

	LIST=`ls *.js`

	# Embed Module ID to *.js 
	for i in $LIST; do
		cat $i | sed "$PATTERN" > ../web_$MODEL/$i
	done


    	### 3. Replace ProductID in *.xml ###

	#PATTERN="s/WL600/$MODEL/g"
	#cat igdevicedesc.xml | sed "$PATTERN" > ../web_$MODEL/igdevicedesc.xml

	### 4. Copy different files for different Model ###
	
	if [ "$MODEL" = "SnapAP" ]; then
		### 4.1 default value ###
		
		
		### 4.2 web page ###	
		cp -f ../web_$MODEL/Advanced_Wireless11g_Content.asp ../web_$MODEL/Advanced_Wireless_Content.asp
		if [ "$MODEL" = "WL300g" ]; then
		cp -f ../web_$MODEL/Advanced_WAdvanced_Content_SNAP.asp ../web_$MODEL/Advanced_WAdvanced_Content.asp
		fi
    		cp -f ../web_$MODEL/Advanced_ACL11g_Content.asp ../web_$MODEL/Advanced_ACL_Content.asp		

		#cp -f ../web_$MODEL/Advanced_DDNS_Content_SNAP.asp ../web_$MODEL/Advanced_DDNS_Content.asp

		#cp -f ../web_$MODEL/Advanced_LANWAN_Content_SNAP.asp ../web_$MODEL/Advanced_LANWAN_Content.asp

		cp -f ../web_$MODEL/Main_WStatus11g_Content.asp ../web_$MODEL/Main_WStatus_Content.asp
		cp -f ../web_$MODEL/Main_Index_HomeGateway11g.asp ../web_$MODEL/Main_Index_HomeGateway.asp
		cp -f ../web_$MODEL/Main_GStatus11g_Content.asp ../web_$MODEL/Main_GStatus_Content.asp
	
		#cp -f ../web_$MODEL/style_SNAP.css ../web_$MODEL/style.css
		
		### 4.3 web graph ###		
		cp -f ../web_$MODEL/graph/iBox_title_all_300g.jpg ../web_$MODEL/graph/iBox_title_all.jpg
		cp -f ../web_$MODEL/graph/internet_all_300.gif ../web_$MODEL/graph/internet_all.gif
		cp -f ../web_$MODEL/graph/internet_none_300.gif ../web_$MODEL/graph/internet_none.gif
		cp -f ../web_$MODEL/graph/internet_some_300.gif ../web_$MODEL/graph/internet_some.gif			
		cp -f ../web_$MODEL/graph/wds_ap_300.gif ../web_$MODEL/graph/wds_ap.gif	
		cp -f ../web_$MODEL/graph/wds_mixed_connect_300.gif ../web_$MODEL/graph/wds_mixed_connect.gif
		cp -f ../web_$MODEL/graph/wds_mixed_anony_300.gif ../web_$MODEL/graph/wds_mixed_anony.gif
		cp -f ../web_$MODEL/graph/wds_mixed_both_300.gif ../web_$MODEL/graph/wds_mixed_both.gif
		cp -f ../web_$MODEL/graph/wds_wds_connect_300.gif ../web_$MODEL/graph/wds_wds_connect.gif
		cp -f ../web_$MODEL/graph/wds_wds_anony_300.gif ../web_$MODEL/graph/wds_wds_anony.gif
		cp -f ../web_$MODEL/graph/wds_wds_both_300.gif ../web_$MODEL/graph/wds_wds_both.gif			
		cp -f ../web_$MODEL/graph/wf_g_300.gif ../web_$MODEL/graph/wf_g.gif	
		cp -f ../web_$MODEL/graph/wf_none_300.gif ../web_$MODEL/graph/wf_none.gif	
		
		### 4.4 Script and module ###

	elif [ "$MODEL" = "WL530g" ]; then
				
		### 4.1 default value ###

		### 4.2 web page ###							
		cp -f ../web_$MODEL/Advanced_Wireless11g_Content.asp ../web_$MODEL/Advanced_Wireless_Content.asp
    		cp -f ../web_$MODEL/Advanced_ACL11g_Content.asp ../web_$MODEL/Advanced_ACL_Content.asp
		cp -f ../web_$MODEL/Main_GStatus11g_Content.asp ../web_$MODEL/Main_GStatus_Content.asp
		cp -f ../web_$MODEL/Main_WStatus11g_Content.asp ../web_$MODEL/Main_WStatus_Content.asp
		cp -f ../web_$MODEL/Main_Index_HomeGateway11g.asp ../web_$MODEL/Main_Index_HomeGateway.asp
		
		### 4.3 web graph ###
		cp -f ../web_$MODEL/graph/iBox_title_all_520g.jpg ./../web_$MODEL/graph/iBox_title_all.jpg
		cp -f ../web_$MODEL/graph/internet_all_500.gif ./../web_$MODEL/graph/internet_all.gif
		cp -f ../web_$MODEL/graph/internet_none_500.gif ./../web_$MODEL/graph/internet_none.gif
		cp -f ../web_$MODEL/graph/internet_some_500.gif ./../web_$MODEL/graph/internet_some.gif			
		cp -f ../web_$MODEL/graph/wds_ap_500.gif ./../web_$MODEL/graph/wds_ap.gif	
		cp -f ../web_$MODEL/graph/wds_mixed_connect_500.gif ./../web_$MODEL/graph/wds_mixed_connect.gif
		cp -f ../web_$MODEL/graph/wds_mixed_anony_500.gif ./../web_$MODEL/graph/wds_mixed_anony.gif
		cp -f ../web_$MODEL/graph/wds_mixed_both_500.gif ./../web_$MODEL/graph/wds_mixed_both.gif
		cp -f ../web_$MODEL/graph/wds_wds_connect_500.gif ./../web_$MODEL/graph/wds_wds_connect.gif
		cp -f ../web_$MODEL/graph/wds_wds_anony_500.gif ./../web_$MODEL/graph/wds_wds_anony.gif
		cp -f ../web_$MODEL/graph/wds_wds_both_500.gif ./../web_$MODEL/graph/wds_wds_both.gif			
		cp -f ../web_$MODEL/graph/wf_g_300.gif ../web_$MODEL/graph/wf_g.gif	
		cp -f ../web_$MODEL/graph/wf_none_300.gif ../web_$MODEL/graph/wf_none.gif		
		
		### 4.4 Script and module ###
	fi


	### 5. Copy web page files to target, except ./target/web/script ###
	cp -rf ../web_$MODEL/. ../target/web
	
	### 6. Remove useless files in ./target/web/* ###
	rm -rf ../target/web/flash.default*
	rm -rf ../target/web/*11g*.asp
	rm -rf ../target/web/*11b*.asp
	rm -rf ../target/web/*_300g.asp	
	rm -f ../target/web/graph/*00g.jpg
	rm -f ../target/web/graph/*_300.gif
	rm -f ../target/web/graph/*_500.gif
	rm -f ../target/web/graph/*_600.gif
	
	### 7. Remove useless files in ./target/* ###
	rm -rf ../target/bin/rc_*
	rm -rf ../target/lib/modules/*.o_8M
	rm -rf ../target/web/graph/AP.gif
	rm -rf ../target/web/graph/Connecting.gif
	rm -rf ../target/web/graph/Disconnect.gif
	rm -rf ../target/web/graph/Firewall.gif
	rm -rf ../target/web/graph/iBox_title_all_500b.jpg
	rm -rf ../target/web/graph/gatewayLog.gif
	rm -rf ../target/web/graph/Upload*.*
	
	### 8. Remove tempdir ###		
	#rm -rf ../web_$MODEL
else
	echo Usage: [ModelID] [Language] [ModelStr]
fi

