#!/bin/bash -x
#
#


# -- write phylogenetic tree
#
echo "(((A,B),C),(D,E));" >| exV.tree

cat << ENDE >| exV.cm
0 { gss{ R,ssA:A,ssB:B } }
ENDE

# -- create a codon model with randomized parameters, and equilibrate.
#
../bin/CodeAxe -create-model -site-model codon -rate-model gy94 -select-model single -root-model obs-avg -tree-file exV.tree -cat-model-file exV.cm -unlock-cat-prob -random-param -reversible-tree |\
cat >| exV.model.random
#../bin/CodeAxe -norm -in-model - >| exV.model.random

# -- simulate sequences from the equilibrated random model
#
../bin/CodeAxe -sim -sim-size 100000 -sim-model discrete -in-model exV.model.random >| exV.data.sim

# self lhood
#
../bin/CodeAxe -lhood -in-model exV.model.random -in-data exV.data.sim >| exV.model.random.lhood



# no cat trained model::
#
# -- create a starting model
#
../bin/CodeAxe -create-model -site-model codon -rate-model gy94 -select-model single -root-model obs-avg -tree-file exV.tree -in-data exV.data.sim -reversible-tree >| exV.model.start

# -- train model
#
../bin/CodeAxe -ml -in-model exV.model.start -in-data exV.data.sim >| exV.model.trained 2>| exV.model.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exV.model.trained -in-data exV.data.sim >| exV.model.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exV.model.trained >| exV.model.trained.report



# branch cat trained_model::
#
# -- create a starting model
#
../bin/CodeAxe -create-model -site-model codon -rate-model gy94 -select-model single -root-model obs-avg -tree-file exV.tree -cat-model-file exV.cm -unlock-cat-prob -in-data exV.data.sim -reversible-tree >| exV.model.2.start

# -- train model
#
../bin/CodeAxe -ml -in-model exV.model.2.start -in-data exV.data.sim >| exV.model.2.trained 2>| exV.model.2.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exV.model.2.trained -in-data exV.data.sim >| exV.model.2.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exV.model.2.trained >| exV.model.2.trained.report

