#!/bin/bash
#
# snappify snapshot management suite
# http://bueller.ca/software/snappify
#
# Copyright (c) 2013 Matt Ferris
# Released under the BSD 2-clause license
# http://bueller.ca/software/snappify/license

# usage: snappify-clean repo

repo=$1
me=`basename "$0"`

if [ -z $repo ]; then
    echo usage: $0 repo
    exit 1
fi

if [ ! -d "$repo" ]; then
    echo error: repository doesn\'t exist, \"$repo\"
    exit 1
fi

if [ ! -d "$repo/snaps" ]; then
    echo error: bad repository, \"$repo/snaps\" doesn\'t exist
    exit 1
fi

if [ ! -d "$repo/meta" ]; then
    echo error: bad repository, \"$repo/meta\" doesn\'t exist
    exit 1
fi

if [ ! -d "$repo/aliases" ]; then
    echo error: bad repository, \"$repo/aliases\" doesn\'t exist
    exit 1
fi

rm -r "$repo/snaps/"* "$repo/aliases/"* "$repo/meta/"* > /dev/null 2>&1

echo cleaned repository $repo
