#!/usr/bin/env sh

include shopts

if shopts_test extglob; then
	SHOPTS_EXTGLOB_SAVE=()
	SHOPTS_EXTGLOB_SAVE_COUNT=0


	shopts_register extglob


	function shopts_extglob_on {
		shopt -s extglob
	}


	function shopts_extglob_off {
		shopt -u extglob
	}


	function shopts_extglob_save {
		SHOPTS_EXTGLOB_SAVE[SHOPTS_EXTGLOB_SAVE_COUNT++]=$(shopt -p extglob)
	}


	function shopts_extglob_restore {
		if [[ SHOPTS_EXTGLOB_SAVE_COUNT -gt 0 ]]; then
			eval "${SHOPTS_EXTGLOB_SAVE[--SHOPTS_EXTGLOB_SAVE_COUNT]}"
			unset SHOPTS_EXTGLOB_SAVE\[SHOPTS_EXTGLOB_SAVE_COUNT\]
		fi
	}


	function shopts_extglob_available {
		true
	}
else
	function shopts_extglob_on { false; }
	function shopts_extglob_off { false; }
	function shopts_extglob_save { false; }
	function shopts_extglob_restore { false; }
	function shopts_extglob_available { false; }
fi
