#!/bin/bash

set -e

case "$1" in
  configure)

    chmod 750 /etc/qigong
    chmod 700 /etc/qigong/keys
    if [ ! -f /etc/qigong/keys/`hostname`.key.priv ]
    then
	cd /etc/qigong/keys && qigenkey `hostname`
    fi
    if [ ! -f /etc/default/qigong ]
    then
	echo "KEYFILE=\""`hostname`.key.priv"\"" > /etc/default/qigong
    fi

    update-rc.d qigong defaults

    if which invoke-rc.d >/dev/null 2>&1; then
	invoke-rc.d qigong restart
    else
	/etc/init.d/qigong restart
    fi
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;; 
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

