#!/bin/bash

if [ $ROCKCFG_ARM_OPT != generic ] ; then
	# Append options so the gcc -V option always comes first.
	# GCC 3.x uses CPU names without '-', eg. 926ejs instead of 926ej-s.
	var_append GCC3_WRAPPER_APPEND " " \
		"-mcpu=${ROCKCFG_ARM_OPT/-s/s}"
	var_append GCC4_WRAPPER_APPEND " " \
		"-mcpu=$ROCKCFG_ARM_OPT"
fi

if [ $ROCKCFG_ARM_OPT_ARCH != generic ] ; then
	var_append GCC3_WRAPPER_APPEND " " \
		"-march=$ROCKCFG_ARM_OPT_ARCH"
	var_append GCC4_WRAPPER_APPEND " " \
		"-march=$ROCKCFG_ARM_OPT_ARCH"
fi
