#!/bin/bash

WORK_DIR="/home/git/mirrors/"
REPO_DIR="/home/git/repositories/"
REPO_URL="$PWD"

if [ $(git rev-parse --is-bare-repository) = true ]
then
    REPO_NAME=${REPO_URL#$REPO_DIR}
    REPO_NAME=${REPO_NAME%.git}
else
    REPO_NAME=$(basename $(readlink -nf "$PWD"/..))
fi

if [ -d "$WORK_DIR/$REPO_NAME" ]; then
    cd "$WORK_DIR/$REPO_NAME"
    unset GIT_DIR
    rm -rf "$WORK_DIR/$REPO_NAME"
    cd "$WORK_DIR"
    git clone -q "$REPO_URL" "$REPO_NAME"
else
    cd "$WORK_DIR"
    git clone -q "$REPO_URL" "$REPO_NAME"
fi

if [ $REPO_NAME != 'gitolite-admin' ]; then
    curl -X POST -d "{ \"repository\": \"$REPO_NAME\" }" -H "Content-Type: application/json" --silent https://devhub.ewi.tudelft.nl/hooks/git-push
fi
