#!/bin/bash -x
#
#



# -- write phylogenetic tree
#
echo "((((A,B),C),(D,E)),F);" >| exY.tree

# -- create a simple nuc model with randomized parameters, and
#    equilibrate model.
#
../bin/CodeAxe -create-model -site-model nuc -rate-model nonrev -root-model full -tree-file exY.tree -cat-model 0{gmo{0}}1{gmo{1}} -unlock-cat-prob -random-param |\
../bin/CodeAxe -norm -in-model - >| exY.model.random
#cat >| exY.model.random

# -- simulate sequences from the equilibrated random model
#
../bin/CodeAxe -sim -sim-size 50000 -sim-model discrete -in-model exY.model.random >| exY.data.sim

# self lhood
#
../bin/CodeAxe -lhood -in-model exY.model.random -in-data exY.data.sim >| exY.model.random.lhood



# test the random model data vs.
# 1) a one category model
# 2) a two category model w/o obs cats
# 3) a two category model w obs cats
#

# -- create a starting model
#
../bin/CodeAxe -create-model -site-model nuc -rate-model nonrev -root-model obs-avg -tree-file exY.tree -in-data exY.data.sim >| exY.model.start

# -- train model
#
../bin/CodeAxe -ml -in-model exY.model.start -in-data exY.data.sim >| exY.model.trained 2>| exY.model.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exY.model.trained -in-data exY.data.sim >| exY.model.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exY.model.trained >| exY.model.trained.report



# -- create a starting model
#
../bin/CodeAxe -create-model -site-model nuc -rate-model nonrev -root-model obs-avg -tree-file exY.tree -cat-model 0{gmm{0}gti{0}}1{gmm{1}gti{0}} -unlock-cat-prob -in-data exY.data.sim -random-param >| exY.model.2.start

# -- train model
#
../bin/CodeAxe -ml -in-model exY.model.2.start -in-data exY.data.sim >| exY.model.2.trained 2>| exY.model.2.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exY.model.2.trained -in-data exY.data.sim >| exY.model.2.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exY.model.2.trained >| exY.model.2.trained.report



# -- create a starting model
#
../bin/CodeAxe -create-model -site-model nuc -rate-model nonrev -root-model obs-avg -tree-file exY.tree -cat-model 0{gmo{0}}1{gmo{1}} -unlock-cat-prob -in-data exY.data.sim -random-param >| exY.model.3.start

# -- train model
#
../bin/CodeAxe -ml -in-model exY.model.3.start -in-data exY.data.sim >| exY.model.3.trained 2>| exY.model.3.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exY.model.3.trained -in-data exY.data.sim >| exY.model.3.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exY.model.3.trained >| exY.model.3.trained.report

