#!/bin/bash


MY_PATH="`dirname \"$0\"`"
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"

source "$MY_PATH/fishlamp-shared.sh" || { echo "[!] unable to load fishlamp-shared.sh"; exit 1; }

count=1
total=${#REPO_LIST[@]}

for repo in ${REPO_LIST[@]}; do
	
	dir="`basename $repo`"
	
	if [ -d "$dir" ]; then

		pushd "$dir" > /dev/null

		log ""
		log "Pulling repo: $dir ($repo) [$count of $total]"

		tab_indent

		current_branch=`git rev-parse --abbrev-ref HEAD` || { echo "unable to get current branch in: $repo"; exit 1; }
		
		run_command "git pull origin $current_branch" "unable to get pull origin $current_branch in $repo"

		tab_outdent
		
		popd > /dev/null
	else 
		log "Repo not found: $dir ($repo) [$count of $total]"
	
	fi

	count=`expr $count + 1` 

done