#!/bin/bash -x
#
#


# -- write phylogenetic tree
#
echo "(((A,B),C) PINKY ,(D,E));" >| exT.tree

cat << ENDE >| exT.cm
0 { gsm{0} gss{ R, ssA:A, ssB:B } }
1 { gsm{1} gss{ R2, ss_pinky_clade:PINKY } }
ENDE

# -- create a codon model with randomized parameters, and equilibrate.
#
../bin/CodeAxe -create-model -site-model codon -rate-model gy94 -select-model single -root-model obs-avg -tree-file exT.tree -cat-model-file exT.cm -unlock-cat-prob -random-param -reversible-tree |\
cat >| exT.model.random
#../bin/CodeAxe -norm -in-model - >| exT.model.random

# -- simulate sequences from the equilibrated random model
#
../bin/CodeAxe -sim -sim-size 100000 -sim-model discrete -in-model exT.model.random >| exT.data.sim

# self lhood
#
../bin/CodeAxe -lhood -in-model exT.model.random -in-data exT.data.sim >| exT.model.random.lhood



# no cat trained model::
#
# -- create a starting model
#
../bin/CodeAxe -create-model -site-model codon -rate-model gy94 -select-model single -root-model obs-avg -tree-file exT.tree -in-data exT.data.sim -reversible-tree >| exT.model.start

# -- train model
#
../bin/CodeAxe -ml -in-model exT.model.start -in-data exT.data.sim >| exT.model.trained 2>| exT.model.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exT.model.trained -in-data exT.data.sim >| exT.model.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exT.model.trained >| exT.model.trained.report



# branch cat trained_model::
#
# -- create a starting model
#
../bin/CodeAxe -create-model -site-model codon -rate-model gy94 -select-model single -root-model obs-avg -tree-file exT.tree -cat-model-file exT.cm -unlock-cat-prob -in-data exT.data.sim -reversible-tree >| exT.model.2.start

# -- train model
#
../bin/CodeAxe -ml -in-model exT.model.2.start -in-data exT.data.sim >| exT.model.2.trained 2>| exT.model.2.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exT.model.2.trained -in-data exT.data.sim >| exT.model.2.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exT.model.2.trained >| exT.model.2.trained.report

