# this script takes the input HTML generated by polymode (alt-n e HTML5)
# and add css styles to make it nicer like in rstudio
# note that you should be in this directory to make it work

usage(){
	echo "Usage: $0 inputHTML outputHTML"
	exit 1
}

# define is_file_exits function 
# $f -> store argument passed to the script
is_file_exits(){
	local f="$1"
	[[ -f "$f" ]] && return 0 || return 1
}

# invoke  usage
# call usage() function if filename not supplied
[[ $# -eq 0 ]] && usage

# Invoke is_file_exits
if ( is_file_exits "$1" )
then
    inputHTML=$1
    outputHTML=$2
    cat RStudioHTML-style > $outputHTML
    cat $inputHTML >> $outputHTML
    echo '</HTML>' >> $outputHTML
else
    echo "Error: incorrect use of the script."
    usage
fi

