#!/bin/sh
. "${SCRIPTDIR}"/common.sh
runfeed 1 << EOF
des -2,-2 j
thres l -2,-2 1
des -4,-2 k
thres h -4,-2 1
thres o -4:-2,-2 0
des 1,-3 j
thres l 1,-3 1
thres o 1,-3 0
des -1,3 o
thres o -1,3 1
des 2,2 m
thres i 2,2 1
thres h 2,2 0
des 3,-1 m
thres l 3,-1 0
thres i 3,-1 1
thres l 6,-2 400
radar 11,-1
lload m 0 20
lload m 1/2/3 1
march 0/1/2/3 5,-1
load m 1 25
load c 1 300
load l 1 100
load h 1 100
load c 2 10
load c 3 10
load land 1 0
load land 2 1
load land 3 2
load land 3 3
build l 10,2 art
nav 2 nh
scrap l 1
y
scrap s 2
y
scuttle l 1
y
scuttle s 2
y
comm 5,-1
scrap l 2
y
comm 5,-1
scrap s 3
y
comm 5,-1
thres i 5,-1 0
thres d 5,-1 0
thres o 5,-1 0
bmap #1
cen *
ship *
land *
map #
read y
prod *
EOF
