# Basic steps, 
#	1. initialize model, d is dimension and c is cluster
#	2. train model with binary data from a file, provide stopping criteria
#	3. model parameters are stored in the output file generated by trainining and additionally cluster inforation can be found by running cluster algorithm
export BMIXPATH=/Users/sohanseth/Dropbox/archetypalAnalysis/Code/bmix-1.11/bin
$BMIXPATH/bmix_init -d $1 -c $2 --min-probability 0.2 --max-probability 0.8 --model-out small.model
$BMIXPATH/bmix_train --data $3 --iterations 1000 --model-out small.final.model --model-in small.model --relative-change 0.000001
$BMIXPATH/bmix_cluster --model-in small.final.model --data $3  > small.final.clusters