#!/bin/bash -x
#
#



# -- write phylogenetic tree
#
echo "(((A,B),C),F);" >| exZ.tree

# -- create a simple nuc model with randomized parameters, and
#    equilibrate model.
#
../bin/CodeAxe -create-model -site-model codon -rate-model gy94 -select-model single -root-model obs-avg -tree-file exZ.tree -reversible-tree \
               -cat-model 0{gmm{0}gsm{0}gob{0}}1{gmm{1}gsm{1}gob{1}} -unlock-cat-prob -random-param |\
../bin/CodeAxe -norm -in-model - >| exZ.model.random

# -- simulate sequences from the equilibrated random model
#
../bin/CodeAxe -sim -sim-size 50000 -in-model exZ.model.random >| exZ.data.sim

# self lhood
#
../bin/CodeAxe -lhood -in-model exZ.model.random -in-data exZ.data.sim >| exZ.model.random.lhood



# test the random model data vs.
# 1) a one category model
# 2) a two category model w/o obs cats
# 3) a two category model w obs cats
#

# -- create a starting model
#
../bin/CodeAxe -create-model -site-model codon -rate-model gy94 -select-model single -root-model obs-avg -tree-file exZ.tree -reversible-tree -in-data exZ.data.sim >| exZ.model.start

# -- train model
#
../bin/CodeAxe -ml -in-model exZ.model.start -in-data exZ.data.sim >| exZ.model.trained 2>| exZ.model.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exZ.model.trained -in-data exZ.data.sim >| exZ.model.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exZ.model.trained >| exZ.model.trained.report



# -- create a starting model
#
../bin/CodeAxe -create-model -site-model codon -rate-model gy94 -select-model single -root-model obs-avg -tree-file exZ.tree -reversible-tree \
               -cat-model 0{gmm{0}gsm{0}}1{gmm{1}gsm{1}} -unlock-cat-prob -in-data exZ.data.sim -random-param >| exZ.model.2.start
# -- train model
#
../bin/CodeAxe -ml -in-model exZ.model.2.start -in-data exZ.data.sim >| exZ.model.2.trained 2>| exZ.model.2.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exZ.model.2.trained -in-data exZ.data.sim >| exZ.model.2.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exZ.model.2.trained >| exZ.model.2.trained.report
       


# -- create a starting model
#
../bin/CodeAxe -create-model -site-model codon -rate-model gy94 -select-model single -root-model obs-avg -tree-file exZ.tree -reversible-tree \
               -cat-model 0{gmm{0}gsm{0}gob{0}}1{gmm{1}gsm{1}gob{1}} -unlock-cat-prob -in-data exZ.data.sim -random-param >| exZ.model.3.start

# -- train model
#
../bin/CodeAxe -ml -in-model exZ.model.3.start -in-data exZ.data.sim >| exZ.model.3.trained 2>| exZ.model.3.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exZ.model.3.trained -in-data exZ.data.sim >| exZ.model.3.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exZ.model.3.trained >| exZ.model.3.trained.report

