#!/bin/bash
#set -e
set -u

users=('devops-workflow')

current_directory=$(pwd)

SyncRepo() {
  repo=$1
  dir="${repo%/*}"
  if [ ! -d "$dir" ]
  then
    echo "Cloning ${repo}"
    git clone "git@github.com:devops-workflow/${repo}.git" "$repo"
  else
    echo "Updating ${repo}"
    cd "$repo"
    git pull
    cd "$current_directory"
  fi
}

SyncUser() {
  user=$1
  for repo in $(curl -s "https://api.github.com/users/$user/repos" | grep \"name\" | cut -d\" -f4)
  do
    if [ "$repo" == $(basename $(pwd)) ]
    then
      continue
    else
      SyncRepo "$repo"
      echo "$repo" >> .gitignore
    fi
  done
}

echo ".git" > .gitignore
echo ".vagrant" >> .gitignore

for user in ${users[@]}
do
  echo "Synching $user"
  SyncUser "$user"
  echo "All done"
done
