#!/bin/bash

error() { printf "%s\n" "$@"; exit 1; }

while test -n "$1" && test ${1:0:1} = -; do
    opt=$1 && shift
    case $opt in
        -v|--verbose)   VERBOSE=1;;
        *) error "unknown option: $opt";;
    esac
done

symvar() {
    name=$1
    test -L "$name" || return
    value="$(readlink $name)"
    value="${value#=}"
    }

files=()

symvar build

for chunk in $value; do

    test -n "$chunk" || continue

    test ${chunk:0:1} = @ && {
        test -e $chunk || error "no list property: $chunk"
        for file in $(<$chunk); do
            files+=($file)
        done
        continue
        }

    test -e "$chunk" || error "no property: $chunk"

    files+=($chunk)
     
done

for f in "${files[@]}"; do
    printf "\n%s:\n" $f
    for g in "${files[@]}"; do
        test $f = $g && continue
        # want to look for g in f
        # but first change '-' to '_'
        h=${g//-/_}
        grep -q $h\( $f &&
          # printf "\t%s\n" $g
            printf "\t%s()\n" $h
    done
done

