#!/bin/bash
#
# shadowmanager main program, the computer science internal assigment.
#
# usage: shadowmanager <command> [arguments ...]
# use './shadowmanager usage' for more informations.

cd "$(dirname "$0")" || exit 1

. ./conf/shadowmanager.conf
. "./lang/$LANGUAGE.lang"

function debug {
        [[ ! -z $DEBUG ]] && echo "[$(echo "${FUNCNAME[*]}"|tr ' ' '/')] $*"
}

function _shadowmanager_load {
        (! grep -q "shadowmanager-ignore" < "$1") && . "./$1" && debug "load: loaded $1" || debug "load: ignored $1"
}

for inc in ./include/*
do
        _shadowmanager_load "$inc"
done

for ovr in ./override/*
do
        _shadowmanager_load "$ovr"
done

ifroot
[[ -z "$@" ]] && usage || shadowmanager_exec "$@"
