#!/bin/bash

LOCAL_REPO=~/.m2/repository/org/clojure
REMOTE_REPO=http://repo1.maven.org/maven2/org/clojure
VERSION=1.2.1
CONTRIB_VERSION=1.2.0

if [ ! -e $LOCAL_REPO/clojure/$VERSION/clojure-$VERSION.jar ]; then
    mkdir -p $LOCAL_REPO/clojure/$VERSION/
    wget -P $LOCAL_REPO/clojure/$VERSION/ -U "" \
        $REMOTE_REPO/clojure/$VERSION/clojure-$VERSION.jar \
        $REMOTE_REPO/clojure/$VERSION/clojure-$VERSION.jar.md5 \
        $REMOTE_REPO/clojure/$VERSION/clojure-$VERSION.jar.sha1 \
        $REMOTE_REPO/clojure/$VERSION/clojure-$VERSION.pom \
        $REMOTE_REPO/clojure/$VERSION/clojure-$VERSION.pom.md5 \
        $REMOTE_REPO/clojure/$VERSION/clojure-$VERSION.pom.sha1
fi

if [ ! -e $LOCAL_REPO/clojure-contrib/$CONTRIB_VERSION/clojure-contrib-$CONTRIB_VERSION.jar ]; then
    mkdir -p $LOCAL_REPO/clojure-contrib/$CONTRIB_VERSION/
    wget -P $LOCAL_REPO/clojure-contrib/$CONTRIB_VERSION/ -U "" \
        $REMOTE_REPO/clojure-contrib/$CONTRIB_VERSION/clojure-contrib-$CONTRIB_VERSION.jar \
        $REMOTE_REPO/clojure-contrib/$CONTRIB_VERSION/clojure-contrib-$CONTRIB_VERSION.jar.md5 \
        $REMOTE_REPO/clojure-contrib/$CONTRIB_VERSION/clojure-contrib-$CONTRIB_VERSION.jar.sha1 \
        $REMOTE_REPO/clojure-contrib/$CONTRIB_VERSION/clojure-contrib-$CONTRIB_VERSION.pom \
        $REMOTE_REPO/clojure-contrib/$CONTRIB_VERSION/clojure-contrib-$CONTRIB_VERSION.pom.md5 \
        $REMOTE_REPO/clojure-contrib/$CONTRIB_VERSION/clojure-contrib-$CONTRIB_VERSION.pom.sha1
fi

exec rlwrap java -Xmx1g $JAVA_OPTS -cp $LOCAL_REPO/clojure/$VERSION/clojure-$VERSION.jar:$LOCAL_REPO/clojure-contrib/$CONTRIB_VERSION/clojure-contrib-$CONTRIB_VERSION.jar clojure.main $@
