#!/bin/bash

# repo_name=$1
# test -z $repo_name && echo "Repo name required." 1>&2 && exit 1
# 
# curl -u "mikefullerton" https://api.github.com/orgs/fishlamp-objc/repos -d "{\"name\":\"$repo_name\"}"
# 
# # git create mynewrepo
# 
# git init
# 
# git remote add origin "https://github.com/your_github_username/$repo_name.git"
# 
# cp "$repo/.gitignore" .gitignore
# cp "$repo/LICENSE" LICENSE
# 
# echo "#$reponame\n" >> README.md
# 
# git add -A
# git commit -a -m "first checkin"
# 
# # import_folder repo path Classes
