//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Referential.Common;

namespace XComponent.Referential.Common.Senders
{
    public class SenderManager
    {
		private static AddInstrumentInstrumentOnReferentialReferentialSender _addInstrumentInstrumentOnReferentialReferentialSender;

        public static AddInstrumentInstrumentOnReferentialReferentialSender AddInstrumentInstrumentOnReferentialReferentialSender
        {
            get
            {
                return _addInstrumentInstrumentOnReferentialReferentialSender ??
                       (_addInstrumentInstrumentOnReferentialReferentialSender = new AddInstrumentInstrumentOnReferentialReferentialSender());
            }
        }

    }
}
