package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldBoolean

/**
  * Generated by SackFix code generator on 20170404
  */
case class NotifyBrokerOfCreditField(override val value: Boolean) extends SfFieldBoolean(208, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(208)NotifyBrokerOfCredit=(").append({if (value) "Y" else "N"}).append(")")
}

object NotifyBrokerOfCreditField {
  val TagId = 208  
  def apply(value: String) = try {
    new NotifyBrokerOfCreditField(value match {
      case "Y" => true
      case "N" => false
      case _ => throw new IllegalArgumentException("NotifyBrokerOfCredit.apply("+value+"] failed, bad value, expected Y or N.")
    })
  } catch {
    case ex: Exception => throw new IllegalArgumentException("new NotifyBrokerOfCredit("+value.toString+") failed with exception", ex)
  } 
  def decode(a: Option[Any]) : Option[NotifyBrokerOfCreditField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[NotifyBrokerOfCreditField]
  }

  def decode(a: Any) : Option[NotifyBrokerOfCreditField] = a match {
    case v: String => Some(NotifyBrokerOfCreditField(v))
    case v: Boolean => Some(NotifyBrokerOfCreditField(v))
    case v: NotifyBrokerOfCreditField => Some(v)
    case _ => scala.Option.empty[NotifyBrokerOfCreditField]
  } 
}
