package org.sackfix.field

import org.sackfix.common.validated.fields.SfFieldString

/**
  * Generated by SackFix code generator on 20170404
  */
case class ContraBrokerField(override val value: String) extends SfFieldString(375, value) {
  override def toString = appendStringBuilder().toString
  override def appendStringBuilder(b:StringBuilder = new StringBuilder()) = b.append("(375)ContraBroker=(").append(value).append(")")
}

object ContraBrokerField {
  val TagId = 375  
  def decode(a: Option[Any]) : Option[ContraBrokerField] = a match {
    case Some(v) => decode(v)
    case _ =>  scala.Option.empty[ContraBrokerField]
  }

  def decode(a: Any) : Option[ContraBrokerField] = a match {
    case v: String => Some(ContraBrokerField(v))
    case v: ContraBrokerField => Some(v)
    case _ => scala.Option.empty[ContraBrokerField]
  } 
}
