package com.schappet.weight.dao;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Generated by Protogen
 * @since 04/07/2015 08:12:26 CDT
 */
@Component
public class WeightDaoService {


	@Autowired
	private ActivityService activityService;

    public ActivityService getActivityService() {
        return activityService;
    }


	@Autowired
	private MetricService metricService;

    public MetricService getMetricService() {
        return metricService;
    }

	@Autowired
	private SummaryTableService summaryTableService;

    public SummaryTableService getSummaryTableService() {
        return summaryTableService;
    }

    
	@Autowired
	private SummaryVitlasService summaryVitalsService;

    public SummaryVitlasService getSummaryVitalsService() {
        return summaryVitalsService;
    }
    
    
	@Autowired
	private EmailAddressService emailAddressService;

    public EmailAddressService getEmailAddressService() {
        return emailAddressService;
    }

	@Autowired
	private PersonService personService;

    public PersonService getPersonService() {
        return personService;
    }
    
	@Autowired
	private VitalsService vitalsService;

    public VitalsService getVitalsService() {
        return vitalsService;
    }

	@Autowired
	private WeightService weightService;

    public WeightService getWeightService() {
        return weightService;
    }

	@Autowired
	private HeartRateService heartRateService;

    public HeartRateService getHeartRateService() {
        return heartRateService;
    }


	@Autowired
	private StepCountService stepCountService;

    public StepCountService getStepCountService() {
        return stepCountService;
    }
}
