package edu.uiowa.icts.safeseed.dao;

import edu.uiowa.icts.spring.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import edu.uiowa.icts.safeseed.dao.*;

/* Generated by Protogen
 *
 *
 *
*/

@Component
public class SafeseedDaoService {

	
	
	private SiteContentService siteContentService;
	

	public SiteContentService getSiteContentService() {
		return siteContentService;
	}
	
	@Autowired 
	public void setSiteContentService(SiteContentService siteContentService) {
		this.siteContentService = siteContentService;
	}

	/*************searchStatusService*****************/
	private SearchStatusService searchStatusService;
	
	public SearchStatusService getSearchStatusService() {
		return searchStatusService;
	}

    @Autowired 
	public void setSearchStatusService(SearchStatusService searchStatusService) {
		this.searchStatusService = searchStatusService;
	}

	/*********** searchResultSerivce ****************/
	private SearchResultService searchResultService;

    public SearchResultService getSearchResultService() {
		return searchResultService;
	}

    @Autowired 
	public void setSearchResultService(SearchResultService searchResultService) {
		this.searchResultService = searchResultService;
	}




	/*********** personService ****************/
    private PersonService personService; 

    public PersonService getPersonService()
    {
        return personService;
    }

    @Autowired 
    public void setPersonService(PersonService personService)
    {
        this.personService = personService;
    }




    /*********** seqService ****************/
    private SeqService seqService; 

    public SeqService getSeqService()
    {
        return seqService;
    }

    @Autowired 
    public void setSeqService(SeqService seqService)
    {
        this.seqService = seqService;
    }




    /*********** fragService ****************/
    private FragService fragService; 

    public FragService getFragService()
    {
        return fragService;
    }

    @Autowired 
    public void setFragService(FragService fragService)
    {
        this.fragService = fragService;
    }




    /*********** systemSettingService ****************/
    private SystemSettingService systemSettingService; 

    public SystemSettingService getSystemSettingService()
    {
        return systemSettingService;
    }

    @Autowired 
    public void setSystemSettingService(SystemSettingService systemSettingService)
    {
        this.systemSettingService = systemSettingService;
    }




    /*********** globalHistoryService ****************/
    private GlobalHistoryService globalHistoryService; 

    public GlobalHistoryService getGlobalHistoryService()
    {
        return globalHistoryService;
    }

    @Autowired 
    public void setGlobalHistoryService(GlobalHistoryService globalHistoryService)
    {
        this.globalHistoryService = globalHistoryService;
    }




    /*********** auditService ****************/
    private AuditService auditService; 

    public AuditService getAuditService()
    {
        return auditService;
    }

    @Autowired 
    public void setAuditService(AuditService auditService)
    {
        this.auditService = auditService;
    }




    /*********** groupService ****************/
    private GroupService groupService; 

    public GroupService getGroupService()
    {
        return groupService;
    }

    @Autowired 
    public void setGroupService(GroupService groupService)
    {
        this.groupService = groupService;
    }




    /*********** groupSeqService ****************/
    private GroupSeqService groupSeqService; 

    public GroupSeqService getGroupSeqService()
    {
        return groupSeqService;
    }

    @Autowired 
    public void setGroupSeqService(GroupSeqService groupSeqService)
    {
        this.groupSeqService = groupSeqService;
    }




    /*********** personGroupService ****************/
    private PersonGroupService personGroupService; 

    public PersonGroupService getPersonGroupService()
    {
        return personGroupService;
    }

    @Autowired 
    public void setPersonGroupService(PersonGroupService personGroupService)
    {
        this.personGroupService = personGroupService;
    }




    /*********** queueService ****************/
    private QueueService queueService; 

    public QueueService getQueueService()
    {
        return queueService;
    }

    @Autowired 
    public void setQueueService(QueueService queueService)
    {
        this.queueService = queueService;
    }




    /*********** seqFragService ****************/
    private SeqFragService seqFragService; 

    public SeqFragService getSeqFragService()
    {
        return seqFragService;
    }

    @Autowired 
    public void setSeqFragService(SeqFragService seqFragService)
    {
        this.seqFragService = seqFragService;
    }




    /*********** submissionService ****************/
    private SubmissionService submissionService; 

    public SubmissionService getSubmissionService()
    {
        return submissionService;
    }

    @Autowired 
    public void setSubmissionService(SubmissionService submissionService)
    {
        this.submissionService = submissionService;
    }




    /*********** globalSeqService ****************/
    private GlobalSeqService globalSeqService; 

    public GlobalSeqService getGlobalSeqService()
    {
        return globalSeqService;
    }

    @Autowired 
    public void setGlobalSeqService(GlobalSeqService globalSeqService)
    {
        this.globalSeqService = globalSeqService;
    }




    /*********** globalSeqFragService ****************/
    private GlobalSeqFragService globalSeqFragService; 

    public GlobalSeqFragService getGlobalSeqFragService()
    {
        return globalSeqFragService;
    }

    @Autowired 
    public void setGlobalSeqFragService(GlobalSeqFragService globalSeqFragService)
    {
        this.globalSeqFragService = globalSeqFragService;
    }




    /*********** seqRelationshipService ****************/
    private SeqRelationshipService seqRelationshipService; 

    public SeqRelationshipService getSeqRelationshipService()
    {
        return seqRelationshipService;
    }

    @Autowired 
    public void setSeqRelationshipService(SeqRelationshipService seqRelationshipService)
    {
        this.seqRelationshipService = seqRelationshipService;
    }




    /*********** collectionService ****************/
    private CollectionService collectionService; 

    public CollectionService getCollectionService()
    {
        return collectionService;
    }

    @Autowired 
    public void setCollectionService(CollectionService collectionService)
    {
        this.collectionService = collectionService;
    }




    /*********** globalCollectionService ****************/
    private GlobalCollectionService globalCollectionService; 

    public GlobalCollectionService getGlobalCollectionService()
    {
        return globalCollectionService;
    }

    @Autowired 
    public void setGlobalCollectionService(GlobalCollectionService globalCollectionService)
    {
        this.globalCollectionService = globalCollectionService;
    }




    /*********** historyService ****************/
    private HistoryService historyService; 

    public HistoryService getHistoryService()
    {
        return historyService;
    }

    @Autowired 
    public void setHistoryService(HistoryService historyService)
    {
        this.historyService = historyService;
    }




    /*********** globalFragService ****************/
    private GlobalFragService globalFragService; 

    public GlobalFragService getGlobalFragService()
    {
        return globalFragService;
    }

    @Autowired 
    public void setGlobalFragService(GlobalFragService globalFragService)
    {
        this.globalFragService = globalFragService;
    }




    /*********** groupGlobalSeqService ****************/
    private GroupGlobalSeqService groupGlobalSeqService; 

    public GroupGlobalSeqService getGroupGlobalSeqService()
    {
        return groupGlobalSeqService;
    }

    @Autowired 
    public void setGroupGlobalSeqService(GroupGlobalSeqService groupGlobalSeqService)
    {
        this.groupGlobalSeqService = groupGlobalSeqService;
    }


}
