package g3.hibernate.entity;
// Generated Jun 5, 2013 8:44:18 AM by Hibernate Tools 3.2.1.GA



/**
 * ManagePermissionMapping generated by hbm2java
 */
public class ManagePermissionMapping  implements java.io.Serializable {


     private ManagePermissionMappingId id;

    public ManagePermissionMapping() {
    }

    public ManagePermissionMapping(ManagePermissionMappingId id) {
       this.id = id;
    }
   
    public ManagePermissionMappingId getId() {
        return this.id;
    }
    
    public void setId(ManagePermissionMappingId id) {
        this.id = id;
    }




}


