#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: e4c3831a-151a-4b5b-ba08-68caf2624652
# Source File: ..\..\..\Documents\SAPIEN\Files\Sharing Events.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
fwoAAB+LCAAAAAAABADVVl1vmzAUfZ+0/2D5GZFAQpNIBGllizat3aqSdXs15NJ6NXZkm7Ts1898
JGpLmtCojTYhIQzncu6591yDfwmJWIEsPhJNkLlQVPApdnHw/h1C/ndJryknbEYZfCMZBNENkZRf
o08r4FrZS5X6vRaoDo1/Q6KRLpYwxVGhNGT2T8oX4k7ZMyGz+myhbY8sdNVkMrT75WGhMGc6lzDl
kGtJmIUu8pjR5CsUc3ELfBqPRsRLvBNnMhhCfzzBiJtUpjg173MwSm4oW0iDw6HgWgqmaoUm0Qsp
liB10QSEjBppEf0DOHDHQwudDPzeGvNMTKkaBxXVXuwc7jUOSplt6P6aneZaC/7mVYsrGndX3drK
zkRCtKHHgTMZWchxWwKfq1xD1wFf92XkWchtt2VLsUn8hS/g3qTUBV21pnsyPxRcUZUTFumCwSlJ
bkPBhMTBXOawLb6amib4XOQKzoCsNvqrhd+rQDtiPpfzuo6pFo9jzEBWNvpHTbVzGNs1nhkEDs5p
IoUSqUYR4QpFIGlqobHtekvdoVEPnOkeYMwu3jnYmP0XGrNLMv+BMR8vPigFmTERqDW2uVMEmUqE
ZDR+BSP6vc1bn7LU1j8Gx6uP137G8tt+HCJJ7szfwSFc/UHqpaPUcRZenwzIfq5fGTuOJiqNTYUs
zKazogkc1LIXqwuFhKPIa1SZLcFIewNtm2U9237v4Q9n8Bd59hDZfwoAAA==#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.99
     Generated on:       12-1-2016 11:08
     Generated by:        
     Organization:        
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2015
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-Sharing_Events_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$button2 = New-Object 'System.Windows.Forms.Button'
	$button1 = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$buttonHover = {
	    $script:oldColor = $this.BackColor
	    $this.BackColor = 'White'
	}
	
	$buttonLeave={
		$this.BackColor = $script:oldColor
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$button2.remove_MouseLeave($buttonLeave)
			$button2.remove_MouseHover($buttonHover)
			$button1.remove_MouseLeave($buttonLeave)
			$button1.remove_MouseHover($buttonHover)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($button2)
	$form1.Controls.Add($button1)
	$form1.ClientSize = '284, 63'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	#
	# button2
	#
	$button2.Location = '197, 12'
	$button2.Name = 'button2'
	$button2.Size = '75, 23'
	$button2.TabIndex = 1
	$button2.Text = 'button2'
	$button2.UseVisualStyleBackColor = $True
	$button2.add_MouseLeave($buttonLeave)
	$button2.add_MouseHover($buttonHover)
	#
	# button1
	#
	$button1.Font = 'Microsoft Sans Serif, 8.25pt'
	$button1.Location = '12, 12'
	$button1.Name = 'button1'
	$button1.Size = '75, 23'
	$button1.TabIndex = 0
	$button1.Text = 'button1'
	$button1.UseVisualStyleBackColor = $True
	$button1.add_MouseLeave($buttonLeave)
	$button1.add_MouseHover($buttonHover)
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Call-Sharing_Events_psf | Out-Null
