<#
Module manifest for the cFirewall module.
Generated by Serge Nikalaichyk (https://www.linkedin.com/in/nikalaichyk)
#>

@{

# Version number of this module.
ModuleVersion = '1.0.1'

# ID used to uniquely identify this module
GUID = 'fdbb9e07-1574-443b-bdfa-a7b1b369bc01'

# Author of this module
Author = 'Serge Nikalaichyk'

# Copyright statement for this module
Copyright = '(c) 2015 Serge Nikalaichyk. All rights reserved.'

# Description of the functionality provided by this module
Description = 'The cFirewall module contains the cFirewallRule DSC resource that provides a mechanism to manage firewall rules. Supports Windows Server 2008 R2 and later.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('DSC', 'DesiredStateConfiguration', 'Firewall', 'INetFwRule', 'NetFirewallRule', 'Network', 'PSModule')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/SNikalaichyk/cFirewall/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/SNikalaichyk/cFirewall'

    }

}

}

