#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 8af71953-a6ee-4b66-9c1f-602e9fa8b768
# Source File: C:\Users\ostojicm\Desktop\Neke skripate\CredMan.psf
#------------------------------------------------------------------------

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.85
     Generated on:       5/29/2015 12:43 PM
     Generated by:       ostojicm
     Organization:       Bugi
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2015
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-CredMan_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$Menu = New-Object 'System.Windows.Forms.Form'
	$OKButton = New-Object 'System.Windows.Forms.Button'
	$Mail = New-Object 'System.Windows.Forms.CheckBox'
	$Portal = New-Object 'System.Windows.Forms.CheckBox'
	$TMG = New-Object 'System.Windows.Forms.CheckBox'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$Menu_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$OKButton_Click= {
		#TODO: Place custom script here
		
		if ($TMG.Checked)
		{
			if ($Mail.Checked)
			{
				cmdkey /add:10.1.1.1 /user:$fcsDomain\$fcsUsername /pass:$fcsPass
				$Menu.Close()
			}
			else
			{
				$fcsCred = Get-Credential -Message "FCS"
				$fcs = $fcsCred.GetNetworkCredential()
				$fcsDomain = $fcs.Domain
				$fcsUserName = $fcs.UserName
				$fcsPass = $fcs.Password
				cmdkey /add:beg-ccr01.fcs.yu /user:$fcsDomain\$fcsUsername /pass:$fcsPass
				$Menu.Close()
			}
		}
		if ($Portal.Checked)
		{
			$ucCred = Get-Credential -Message "UC"
			$uc = $ucCred.GetNetworkCredential()
			$ucDomain = $uc.Domain
			$ucPass = $uc.Password
			$ucUserName = $uc.UserName
			cmdkey /add:10.0.5.48 /user:$UCDOmain\$UCUsername /pass:$UCPass
			$Menu.Close()
		}
		if ($Mail.Checked)
		{
			if ($TMG.Checked)
			{
				
				cmdkey /add:beg-ccr01.fcs.yu /user:$fcsDomain\$fcsUsername /pass:$fcsPass
				$Menu.Close()
			}
			else
			{
				$fcsCred = Get-Credential -Message "FCS"
				$fcs = $fcsCred.GetNetworkCredential()
				$fcsDomain = $fcs.Domain
				$fcsUserName = $fcs.UserName
				$fcsPass = $fcs.Password
				cmdkey /add:beg-ccr01.fcs.yu /user:$fcsDomain\$fcsUsername /pass:$fcsPass
				$Menu.Close()
			}
			
		}
	}
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$Menu.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$OKButton.remove_Click($OKButton_Click)
			$Menu.remove_Load($Menu_Load)
			$Menu.remove_Load($Form_StateCorrection_Load)
			$Menu.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$Menu.SuspendLayout()
	#
	# Menu
	#
	$Menu.Controls.Add($OKButton)
	$Menu.Controls.Add($Mail)
	$Menu.Controls.Add($Portal)
	$Menu.Controls.Add($TMG)
	$Menu.ClientSize = '291, 250'
	$Menu.Font = "Arial, 8.25pt"
	$Menu.FormBorderStyle = 'FixedDialog'
	$Menu.MaximizeBox = $False
	$Menu.MinimizeBox = $False
	$Menu.Name = "Menu"
	$Menu.StartPosition = 'CenterScreen'
	$Menu.Text = "Menu"
	$Menu.add_Load($Menu_Load)
	#
	# OKButton
	#
	$OKButton.Font = "Arial, 8.25pt"
	$OKButton.Location = '192, 202'
	$OKButton.Name = "OKButton"
	$OKButton.Size = '73, 23'
	$OKButton.TabIndex = 3
	$OKButton.Text = "OK"
	$OKButton.UseVisualStyleBackColor = $True
	$OKButton.add_Click($OKButton_Click)
	#
	# Mail
	#
	$Mail.Font = "Arial, 8.25pt"
	$Mail.Location = '14, 142'
	$Mail.Name = "Mail"
	$Mail.Size = '106, 25'
	$Mail.TabIndex = 2
	$Mail.Text = "Mail"
	$Mail.UseVisualStyleBackColor = $True
	#
	# Portal
	#
	$Portal.Font = "Arial, 8.25pt"
	$Portal.Location = '13, 86'
	$Portal.Name = "Portal"
	$Portal.Size = '107, 26'
	$Portal.TabIndex = 1
	$Portal.Text = "Portal"
	$Portal.UseVisualStyleBackColor = $True
	#
	# TMG
	#
	$TMG.Font = "Arial, 8.25pt"
	$TMG.Location = '14, 34'
	$TMG.Name = "TMG"
	$TMG.Size = '106, 27'
	$TMG.TabIndex = 0
	$TMG.Text = "Internet"
	$TMG.UseVisualStyleBackColor = $True
	$Menu.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $Menu.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$Menu.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$Menu.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $Menu.ShowDialog()

} #End Function

#Call the form
Call-CredMan_psf | Out-Null
