#
# Module manifest for module 'KeyVaultManager'
#
# Generated by: Microsoft Corp.
#
# Generated on: 11/9/2014
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'c77b87c3-f0c0-4c11-8b57-29cd6dcefeb1'

# Author of this module
Author = 'Microsoft Corp.'

# Company or vendor of this module
CompanyName = 'Microsoft Corp.'

# Copyright statement for this module
Copyright = '(c) 2014 Microsoft Corp. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module contains sample code to manage Azure key vaults'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = 'KeyVaultManager.Format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = 'KeyVaultManager.psm1'

# Functions to export from this module
FunctionsToExport = 'New-AzureKeyVault', 'Set-AzureKeyVaultAccessPolicy', 'Remove-AzureKeyVault', 'Get-AzureKeyVault', 'Remove-AzureKeyVaultAccessPolicy', `
                    'Connect-AzureAD', 'Get-AzureADApplication', 'Add-AzureADApplicationCredential', 'New-AzureADApplication'

# Cmdlets to export from this module
# CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'KeyVaultManager.psd1', 'KeyVaultManager.psm1', 'KeyVaultManager.psm1-help.xml'

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

