#
# Module manifest for module 'coreos-hyperv'
#
# Generated by: Paul Shirley
#
# Generated on: 29/08/2014
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\modules\coreos-hyperv.psm1'

# Version number of this module.
ModuleVersion = '0.3'

# ID used to uniquely identify this module
GUID = 'c10047ca-3b1d-4f72-b74b-a2a5522add42'

# Author of this module
Author = 'Paul Shirley'

# Company or vendor of this module
CompanyName = 'None'

# Copyright statement for this module
Copyright = '(c) 2014 Paul Shirley. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A module containing functions to create and manage clusters of coreos Hyper-V virtual machines.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Hyper-V')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    '.\modules\coreos-hyperv-functions.psm1',
    '.\modules\coreos-hyperv-images.psm1',
    '.\modules\coreos-hyperv-config.psm1')

# Functions to export from this module
FunctionsToExport = @(
    '*-CoreosCluster',
    '*-CoreosVM',
    '*-CoreosConfig',
    '*-CoreosNetworkConfig',
    'New-EtcdDiscoveryToken',
    'Get-CoreosFilesDirectory',
    'Get-CoreosCurrentReleaseNumber')
# FunctionsToExport = '*'

# Cmdlets to export from this module
# CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @('files')

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

