<#
    .NOTES
    --------------------------------------------------------------------------------
     Windows Forms generated by: PowerShell Studio 2014 v4.1.60
     Generated on:       11-06-2014 21:51
     Generated by:       Michael Buchardt
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Get User ID from input and passes it to TS
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-GetuserID_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$Blog = New-Object 'System.Windows.Forms.Form'
	$buttonRunOSDeployment = New-Object 'System.Windows.Forms.Button'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$labelPleaseEnterAUserID = New-Object 'System.Windows.Forms.Label'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	$OnLoadFormEvent={
	#Hide the task sequence progress dialog until next step
	    $TSProgressUI = new-object -comobject Microsoft.SMS.TSProgressUI
	    $TSProgressUI.CloseProgressDialog()
	}
	
	$labelPleaseEnterAUserID_Click={
			
	}
	
	$buttonRunOSDeployment_Click={
		#Get User ID from input
		$UserID = $textbox1.Text
		
		#Send User ID to SCCM TS
		$tsenv = New-Object -ComObject Microsoft.SMS.TSEnvironment
		$tsenv.Value("UserID") = "$UserID"
				
		#Close form and Exit Script when RunOSDeployButton is clicked
		$Blog.Close() 
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$Blog.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonRunOSDeployment.remove_Click($buttonRunOSDeployment_Click)
			$labelPleaseEnterAUserID.remove_Click($labelPleaseEnterAUserID_Click)
			$Blog.remove_Load($OnLoadFormEvent)
			$Blog.remove_Load($Form_StateCorrection_Load)
			$Blog.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$Blog.SuspendLayout()
	#
	# Blog
	#
	$Blog.Controls.Add($buttonRunOSDeployment)
	$Blog.Controls.Add($textbox1)
	$Blog.Controls.Add($labelPleaseEnterAUserID)
	$Blog.AcceptButton = $buttonRunOSDeployment
	$Blog.ClientSize = '364, 181'
	$Blog.ControlBox = $False
	$Blog.Font = "Microsoft Sans Serif, 12pt"
	$Blog.KeyPreview = $True
	$Blog.MaximizeBox = $False
	$Blog.MinimizeBox = $False
	$Blog.Name = "Blog"
	$Blog.ShowIcon = $False
	$Blog.StartPosition = 'CenterScreen'
	$Blog.Text = "Get User ID"
	$Blog.add_Load($OnLoadFormEvent)
	#
	# buttonRunOSDeployment
	#
	$buttonRunOSDeployment.Font = "Microsoft Sans Serif, 14pt, style=Bold"
	$buttonRunOSDeployment.ForeColor = 'MenuHighlight'
	$buttonRunOSDeployment.Location = '97, 98'
	$buttonRunOSDeployment.Name = "buttonRunOSDeployment"
	$buttonRunOSDeployment.Size = '167, 68'
	$buttonRunOSDeployment.TabIndex = 2
	$buttonRunOSDeployment.Text = "Run OS deployment"
	$buttonRunOSDeployment.UseVisualStyleBackColor = $True
	$buttonRunOSDeployment.add_Click($buttonRunOSDeployment_Click)
	#
	# textbox1
	#
	$textbox1.AcceptsReturn = $True
	$textbox1.Font = "Microsoft Sans Serif, 14pt"
	$textbox1.Location = '97, 46'
	$textbox1.MaxLength = 15
	$textbox1.Name = "textbox1"
	$textbox1.Size = '167, 29'
	$textbox1.TabIndex = 1
	#
	# labelPleaseEnterAUserID
	#
	$labelPleaseEnterAUserID.Font = "Microsoft Sans Serif, 16pt, style=Bold"
	$labelPleaseEnterAUserID.Location = '54, 9'
	$labelPleaseEnterAUserID.Name = "labelPleaseEnterAUserID"
	$labelPleaseEnterAUserID.Size = '252, 34'
	$labelPleaseEnterAUserID.TabIndex = 0
	$labelPleaseEnterAUserID.Text = "Please enter a user ID"
	$labelPleaseEnterAUserID.add_Click($labelPleaseEnterAUserID_Click)
	$Blog.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $Blog.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$Blog.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$Blog.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $Blog.ShowDialog()

} #End Function

#Call the form
Call-GetuserID_psf | Out-Null