#
#Some Plumbing vars
$currentPath = $(Split-Path $MyInvocation.MyCommand.Path)
$Command ="$currentPath\packages\autorest.0.11.0\tools\AutoRest.exe"

$currentPath

#Client prefix, for convenience
$apiTag = "AltNetClient"

#Url with Swagger Definition
$swaggerDefinitionUrl = "http://localhost:9999/swagger/docs/v1"

#File to save Swagger definition to
$outputJsonFileName = "$currentPath\$apiTag.swagger.json"

#Namespace for generated classes
$ClientNamespace = "APIClient.$apiTag";

# Output folder for generated classes
$TargetPath = "$currentPath\APIClient\$apiTag";

#Proxy header that will be added to each class
$ProxyHeader += "IMPORTANT: This class is auto-generated. Any changes to it will be lost during proxy re-generation. Generated by AutoRest from $swaggerDefinitionUrl. Visit https://github.com/Azure/autorest for details and usage examples."

# Download swagger definition to file
"Getting data from '$swaggerDefinitionUrl' to '$outputJsonFileName'..."
(Invoke-webrequest -URI $swaggerDefinitionUrl).Content | Set-Content $outputJsonFileName

#Prepare AutoRest command line parameters
$Parameters = @( 
    "-CodeGenerator", "CSharp", 
    "-Modeler", "Swagger",
    "-Input", "$outputJsonFileName",
    "-Namespace", "$ClientNamespace",
    "-OutputDirectory", "$TargetPath",
    "-Header", "$ProxyHeader",
    "-AddCredentials", "true")

# Execute autorest to generate proxy
"Generating Proxy classes..."
& $Command $Parameters
"All Done!"
