//==========================================================================//
// 이 파일은 export_interface.lua 스크립트에 의해 자동생성된 코드입니다.
// 직접 수정하지 마십시오.
// 10/03/16 10:31:25
//==========================================================================//


ZL_REGISTER( QF_CameraworkingNpc            )
ZL_REGISTER( QF_CameraworkingPoint          )
ZL_REGISTER( QF_CameraworkingSelf           )
ZL_REGISTER( QF_ChangetalkImage             )
ZL_REGISTER( QF_ChangetalkName              )
ZL_REGISTER( QF_EffectCallNpc               )
ZL_REGISTER( QF_EffectCallSelf              )
ZL_REGISTER( QF_MotionCallNpc               )
ZL_REGISTER( QF_MotionCallSelf              )
ZL_REGISTER( QF_NpcHide                     )
ZL_REGISTER( QF_NpcTalkinterfaceHide        )
ZL_REGISTER( QF_NpcTalkinterfaceView        )
ZL_REGISTER( QF_NpcView                     )
ZL_REGISTER( QF_appendQuest                 )
ZL_REGISTER( QF_beginCon                    )
ZL_REGISTER( QF_checkQuestCondition         )
ZL_REGISTER( QF_closeCon                    )
ZL_REGISTER( QF_deleteQuest                 )
ZL_REGISTER( QF_doQuestTrigger              )
ZL_REGISTER( QF_findQuest                   )
ZL_REGISTER( QF_getClanVAR                  )
ZL_REGISTER( QF_getEpisodeVAR               )
ZL_REGISTER( QF_getEventOwner               )
ZL_REGISTER( QF_getJobVAR                   )
ZL_REGISTER( QF_getNpcQuestZeroVal          )
ZL_REGISTER( QF_getPlanetVAR                )
ZL_REGISTER( QF_getQuestCount               )
ZL_REGISTER( QF_getQuestID                  )
ZL_REGISTER( QF_getQuestItemQuantity        )
ZL_REGISTER( QF_getQuestSwitch              )
ZL_REGISTER( QF_getQuestVar                 )
ZL_REGISTER( QF_getSkillLevel               )
ZL_REGISTER( QF_getUnionVAR                 )
ZL_REGISTER( QF_getUserSwitch               )
ZL_REGISTER( QF_givePoint                   )
ZL_REGISTER( QF_gotoCon                     )
// end of file
