/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

IF OBJECT_ID('view_employee', 'U') IS NOT NULL
  DROP TABLE [view_employee];
GO

IF OBJECT_ID('view_employer', 'U') IS NOT NULL
  DROP TABLE [view_employer];
GO

IF OBJECT_ID('view_country', 'U') IS NOT NULL
  DROP TABLE [view_country];
GO

CREATE TABLE [view_country] (
  [code] VARCHAR(256) NOT NULL PRIMARY KEY,
  [name] VARCHAR(512) NOT NULL);
GO

CREATE TABLE [view_employer] (
  [id] BIGINT NOT NULL PRIMARY KEY,
  [name] VARCHAR(512) NOT NULL);
GO

CREATE TABLE [view_employee] (
  [id] BIGINT NOT NULL PRIMARY KEY,
  [first] VARCHAR(512) NOT NULL,
  [last] VARCHAR(512) NOT NULL,
  [age] SMALLINT NOT NULL,
  [residence] VARCHAR(256) NULL,
  [nationality] VARCHAR(256) NULL,
  [employed_by] BIGINT NULL
  /*
  CONSTRAINT [view_employee_residence_fk]
    FOREIGN KEY ([residence])
    REFERENCES [view_country] ([code])
  */
  /*
  CONSTRAINT [view_employee_nationality_fk]
    FOREIGN KEY ([nationality])
    REFERENCES [view_country] ([code])
  */
  /*
  CONSTRAINT [view_employee_employed_by_fk]
    FOREIGN KEY ([employed_by])
    REFERENCES [view_employer] ([id])
  */);
GO

