/******************************************************************************/
/****               Generated by IBExpert 18/04/05 17:28:18                ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE EQSALDOLOTE (
    CODEMP         INTEGER NOT NULL,
    CODFILIAL      SMALLINT NOT NULL,
    CODPROD        INTEGER NOT NULL,
    CODLOTE           CHAR(13) NOT NULL,
    CODEMPAX       INTEGER NOT NULL,
    CODFILIALAX    SMALLINT NOT NULL,
    CODALMOX       INTEGER NOT NULL,
    SLDLOTE        NUMERICDN DEFAULT 0 NOT NULL /* NUMERICDN = NUMERIC(15,5) */,
    SLDRESLOTE     NUMERICDN DEFAULT 0 NOT NULL /* NUMERICDN = NUMERIC(15,5) */,
    SLDCONSIGLOTE  NUMERICDN DEFAULT 0 NOT NULL /* NUMERICDN = NUMERIC(15,5) */,
    SLDLIQLOTE     NUMERICDN DEFAULT 0 NOT NULL /* NUMERICDN = NUMERIC(15,5) */,
    DTINS          DATE DEFAULT 'now',
    IDUSUINS       CHAR(8) DEFAULT USER,
    DTALT          DATE DEFAULT 'now',
    IDUSUALT       CHAR(8) DEFAULT USER,
    HINS           TIME DEFAULT 'now',
    HALT           TIME DEFAULT 'now'
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE EQSALDOLOTE ADD CONSTRAINT EQSALDOLOTEPK PRIMARY KEY (CODLOTE, CODPROD,  CODFILIAL, CODEMP, CODALMOX, CODFILIALAX, CODEMPAX);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE EQSALDOLOTE ADD CONSTRAINT EQSALDOLOTEFKEQALMOX FOREIGN KEY (CODALMOX, CODFILIALAX, CODEMPAX) REFERENCES EQALMOX (CODALMOX, CODFILIAL, CODEMP);
ALTER TABLE EQSALDOLOTE ADD CONSTRAINT EQSALDOLOTEFKEQLOTE FOREIGN KEY (CODLOTE, CODPROD, CODFILIAL, CODEMP) REFERENCES EQLOTE (CODLOTE, CODPROD, CODFILIAL, CODEMP);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;




/* Trigger: EQSALDOPRODTGBI */
CREATE TRIGGER EQSALDOLOTETGBI FOR EQSALDOLOTE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  if (new.SLDLOTE is null) then
     new.SLDLOTE = 0;
  if (new.SLDRESLOTE is null) then
     new.SLDRESLOTE = 0;
  if (new.SLDCONSIGLOTE is null) then
     new.SLDCONSIGLOTE = 0;
  new.SLDLIQLOTE = new.SLDLOTE-new.SLDRESLOTE-new.SLDCONSIGLOTE;
END
^

/* Trigger: EQSALDOPRODTGBU */
CREATE TRIGGER EQSALDOLOTETGBU FOR EQSALDOLOTE
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  new.DTALT=cast('now' AS DATE);
  new.IDUSUALT=USER;
  new.HALT = cast('now' AS TIME);
  if (new.SLDLOTE is null) then
     new.SLDLOTE = 0;
  if (new.SLDRESLOTE is null) then
     new.SLDRESLOTE = 0;
  if (new.SLDCONSIGLOTE is null) then
     new.SLDCONSIGLOTE = 0;
  new.SLDLIQLOTE = new.SLDLOTE-new.SLDRESLOTE-new.SLDCONSIGLOTE;
END
^


SET TERM ; ^

commit work;
